# @generated by scripts/buckify-crates.py from the workspace's Cargo.toml files and
# from the bar's own cargo invocations (scripts/section.sh). Do not edit: re-run the
# script; `--check` fails when this is not what they render to (GaugeWright BUILD.md
# stage 5).

load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")
load("@prelude//rust:cargo_package.bzl", "cargo")
load("@gaugewright//tools/buck:native_test.bzl", "native_clippy_configuration", "native_lint_suite", "native_test_run", "native_test_suite")

def native_crates():
    native_clippy_configuration(
        name = "clippy-configuration",
    )
    cargo.rust_library(
        name = "rust-gaugedesk-core",
        srcs = glob([
        "platform/crates/core/**"
    ], exclude = [
        "platform/crates/core/tests/**",
        "platform/crates/core/examples/**",
        "platform/crates/core/benches/**",
        "platform/crates/core/target/**"
    ]) + [],
        crate = "gaugedesk_core",
        crate_root = "platform/crates/core/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-core",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_core"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/core"
    ],
        deps = [
        "//third-party:ciborium",
        "//third-party:hex",
        "//third-party:p256",
        "//third-party:serde",
        "//third-party:sha2"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugedesk-directory-protocol",
        srcs = glob([
        "platform/crates/directory-protocol/**"
    ], exclude = [
        "platform/crates/directory-protocol/tests/**",
        "platform/crates/directory-protocol/examples/**",
        "platform/crates/directory-protocol/benches/**",
        "platform/crates/directory-protocol/target/**"
    ]) + [],
        crate = "gaugedesk_directory_protocol",
        crate_root = "platform/crates/directory-protocol/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-directory-protocol",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_directory_protocol"
    },
        features = [
        "default"
    ],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/directory-protocol"
    ],
        deps = [
        "//third-party:serde",
        "//third-party:serde_json",
        ":rust-gaugedesk-core"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugedesk-env",
        srcs = glob([
        "platform/crates/env/**"
    ], exclude = [
        "platform/crates/env/tests/**",
        "platform/crates/env/examples/**",
        "platform/crates/env/benches/**",
        "platform/crates/env/target/**"
    ]) + [],
        crate = "gaugedesk_env",
        crate_root = "platform/crates/env/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-env",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_env"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/env"
    ],
        deps = [],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugedesk-store",
        srcs = glob([
        "platform/crates/store/**"
    ], exclude = [
        "platform/crates/store/tests/**",
        "platform/crates/store/examples/**",
        "platform/crates/store/benches/**",
        "platform/crates/store/target/**"
    ]) + [],
        crate = "gaugedesk_store",
        crate_root = "platform/crates/store/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-store",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_store"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/store"
    ],
        deps = [
        "//third-party:rusqlite",
        "//third-party:serde",
        "//third-party:serde_json",
        ":rust-gaugedesk-core",
        ":rust-gaugedesk-env"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugewright-directory",
        srcs = glob([
        "src/**"
    ]) + [],
        crate = "gaugewright_directory",
        crate_root = "src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugewright-directory",
        "CARGO_PKG_VERSION": "0.0.0",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "0",
        "CARGO_PKG_VERSION_PATCH": "0",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugewright_directory"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory"
    ],
        deps = [
        "//third-party:axum-0_7",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:sha2",
        "//third-party:tokio",
        "//third-party:tracing-subscriber",
        ":rust-gaugedesk-core",
        ":rust-gaugedesk-directory-protocol",
        ":rust-gaugedesk-store"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_binary(
        name = "rust-bin-gaugewright-directory",
        srcs = glob([
        "src/**"
    ]) + [],
        crate = "gaugewright_directory",
        crate_root = "src/main.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugewright-directory",
        "CARGO_PKG_VERSION": "0.0.0",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "0",
        "CARGO_PKG_VERSION_PATCH": "0",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugewright_directory",
        "CARGO_BIN_NAME": "gaugewright-directory"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory"
    ],
        deps = [
        "//third-party:axum-0_7",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:sha2",
        "//third-party:tokio",
        "//third-party:tracing-subscriber",
        ":rust-gaugedesk-core",
        ":rust-gaugedesk-directory-protocol",
        ":rust-gaugedesk-store",
        ":rust-gaugewright-directory"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugedesk-boundary--2dc936c0",
        srcs = glob([
        "platform/crates/boundary/**"
    ], exclude = [
        "platform/crates/boundary/tests/**",
        "platform/crates/boundary/examples/**",
        "platform/crates/boundary/benches/**",
        "platform/crates/boundary/target/**"
    ]) + [],
        crate = "gaugedesk_boundary",
        crate_root = "platform/crates/boundary/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-boundary",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_boundary"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/boundary"
    ],
        deps = [
        "//third-party:serde",
        "//third-party:serde_json",
        ":rust-gaugedesk-core"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugedesk-harness--485fa18b",
        srcs = glob([
        "platform/crates/harness/**"
    ], exclude = [
        "platform/crates/harness/tests/**",
        "platform/crates/harness/examples/**",
        "platform/crates/harness/benches/**",
        "platform/crates/harness/target/**"
    ]) + [],
        crate = "gaugedesk_harness",
        crate_root = "platform/crates/harness/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-harness",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_harness"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/harness"
    ],
        deps = [
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:tokio",
        "//third-party:tracing",
        ":rust-gaugedesk-env"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugedesk-relay-transport--bee270ff",
        srcs = glob([
        "platform/crates/relay-transport/**"
    ], exclude = [
        "platform/crates/relay-transport/tests/**",
        "platform/crates/relay-transport/examples/**",
        "platform/crates/relay-transport/benches/**",
        "platform/crates/relay-transport/target/**"
    ]) + [],
        crate = "gaugedesk_relay_transport",
        crate_root = "platform/crates/relay-transport/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-relay-transport",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_relay_transport"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/relay-transport"
    ],
        deps = [
        "//third-party:base64",
        "//third-party:futures-util",
        "//third-party:getrandom-0_2",
        "//third-party:hex",
        "//third-party:rcgen",
        "//third-party:rustls",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:sha2",
        "//third-party:tokio",
        "//third-party:tokio-rustls",
        "//third-party:tokio-tungstenite",
        ":rust-gaugedesk-env"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugedesk-tracker--222fae4e",
        srcs = glob([
        "platform/crates/tracker/**"
    ], exclude = [
        "platform/crates/tracker/tests/**",
        "platform/crates/tracker/examples/**",
        "platform/crates/tracker/benches/**",
        "platform/crates/tracker/target/**"
    ]) + [],
        crate = "gaugedesk_tracker",
        crate_root = "platform/crates/tracker/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-tracker",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_tracker"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/tracker"
    ],
        deps = [
        "//third-party:serde_json",
        "//third-party:whipplescript-kernel",
        "//third-party:whipplescript-store"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugedesk-whip-runtime--0b7b7083",
        srcs = glob([
        "platform/crates/whip-runtime/**"
    ], exclude = [
        "platform/crates/whip-runtime/tests/**",
        "platform/crates/whip-runtime/examples/**",
        "platform/crates/whip-runtime/benches/**",
        "platform/crates/whip-runtime/target/**"
    ]) + [
        "platform/contracts/model-token-rates.json"
    ],
        crate = "gaugedesk_whip_runtime",
        crate_root = "platform/crates/whip-runtime/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-whip-runtime",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_whip_runtime"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/whip-runtime"
    ],
        deps = [
        "//third-party:base64",
        "//third-party:hex",
        "//third-party:libc",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:sha2",
        "//third-party:ureq",
        "//third-party:url",
        "//third-party:whipplescript",
        "//third-party:whipplescript-kernel",
        "//third-party:whipplescript-parser",
        "//third-party:whipplescript-store",
        ":rust-gaugedesk-core",
        ":rust-gaugedesk-harness--485fa18b"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugedesk-workspace--51c41ba7",
        srcs = glob([
        "platform/crates/workspace/**"
    ], exclude = [
        "platform/crates/workspace/tests/**",
        "platform/crates/workspace/examples/**",
        "platform/crates/workspace/benches/**",
        "platform/crates/workspace/target/**"
    ]) + [],
        crate = "gaugedesk_workspace",
        crate_root = "platform/crates/workspace/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-workspace",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_workspace"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/workspace"
    ],
        deps = [
        "//third-party:hex",
        "//third-party:rusqlite",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:sha2",
        "//third-party:tempfile",
        "//third-party:whipplescript-kernel",
        "//third-party:whipplescript-store"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    cargo.rust_library(
        name = "rust-gaugedesk-app--aff713e2",
        srcs = glob([
        "platform/crates/app/**"
    ], exclude = [
        "platform/crates/app/tests/**",
        "platform/crates/app/examples/**",
        "platform/crates/app/benches/**",
        "platform/crates/app/target/**"
    ]) + [
        "platform/sidecar/codex-oauth-login.mjs"
    ],
        crate = "gaugedesk_app",
        crate_root = "platform/crates/app/src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugedesk-app",
        "CARGO_PKG_VERSION": "0.4.21",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "4",
        "CARGO_PKG_VERSION_PATCH": "21",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugedesk_app"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory/platform/crates/app"
    ],
        deps = [
        "//third-party:axum",
        "//third-party:base64",
        "//third-party:directories",
        "//third-party:futures",
        "//third-party:getrandom-0_2",
        "//third-party:hex",
        "//third-party:image",
        "//third-party:jsonwebtoken",
        "//third-party:listenfd",
        "//third-party:p256",
        "//third-party:passkey-auth",
        "//third-party:rcgen",
        "//third-party:ring",
        "//third-party:semver",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:sha2",
        "//third-party:tempfile",
        "//third-party:tokio",
        "//third-party:tokio-rustls",
        "//third-party:tokio-stream",
        "//third-party:tower-http",
        "//third-party:tracing",
        "//third-party:tracing-subscriber",
        "//third-party:ureq",
        "//third-party:url",
        "//third-party:whipplescript-kernel",
        "//third-party:whipplescript-store",
        ":rust-gaugedesk-boundary--2dc936c0",
        ":rust-gaugedesk-core",
        ":rust-gaugedesk-directory-protocol",
        ":rust-gaugedesk-env",
        ":rust-gaugedesk-harness--485fa18b",
        ":rust-gaugedesk-relay-transport--bee270ff",
        ":rust-gaugedesk-store",
        ":rust-gaugedesk-tracker--222fae4e",
        ":rust-gaugedesk-whip-runtime--0b7b7083",
        ":rust-gaugedesk-workspace--51c41ba7"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    native.rust_test(
        name = "rust-test-gaugewright-directory-lib--build",
        srcs = glob([
        "src/**"
    ]) + [],
        crate = "gaugewright_directory",
        crate_root = "src/lib.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugewright-directory",
        "CARGO_PKG_VERSION": "0.0.0",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "0",
        "CARGO_PKG_VERSION_PATCH": "0",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugewright_directory"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory"
    ],
        deps = [
        "//third-party:axum-0_7",
        "//third-party:proptest",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:sha2",
        "//third-party:tempfile",
        "//third-party:tokio",
        "//third-party:tracing-subscriber",
        "//third-party:ureq",
        ":rust-gaugedesk-app--aff713e2",
        ":rust-gaugedesk-core",
        ":rust-gaugedesk-directory-protocol",
        ":rust-gaugedesk-store"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    native_test_run(
        name = "rust-test-gaugewright-directory-lib--build-run",
        test = ":rust-test-gaugewright-directory-lib--build",
        bins = {
        "gaugewright-directory": ":rust-bin-gaugewright-directory"
    },
        artifacts = {},
        data = glob([
        "Cargo.toml",
        "src/**",
        "tests/**"
    ], exclude = [
        "**/target/**",
        "**/node_modules/**"
    ]),
        cell = "gaugewright-directory",
        crate_dir = ".",
        fixed_root = "/mnt/gaugewright-native",
        default_target_platform = "prelude//platforms:default",
    )
    native.rust_test(
        name = "rust-test-gaugewright-directory-bin-gaugewright-directory--build",
        srcs = glob([
        "src/**"
    ]) + [],
        crate = "gaugewright_directory",
        crate_root = "src/main.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugewright-directory",
        "CARGO_PKG_VERSION": "0.0.0",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "0",
        "CARGO_PKG_VERSION_PATCH": "0",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "gaugewright_directory"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory"
    ],
        deps = [
        "//third-party:axum-0_7",
        "//third-party:proptest",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:sha2",
        "//third-party:tempfile",
        "//third-party:tokio",
        "//third-party:tracing-subscriber",
        "//third-party:ureq",
        ":rust-gaugedesk-app--aff713e2",
        ":rust-gaugedesk-core",
        ":rust-gaugedesk-directory-protocol",
        ":rust-gaugedesk-store",
        ":rust-gaugewright-directory"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    native_test_run(
        name = "rust-test-gaugewright-directory-bin-gaugewright-directory--build-run",
        test = ":rust-test-gaugewright-directory-bin-gaugewright-directory--build",
        bins = {
        "gaugewright-directory": ":rust-bin-gaugewright-directory"
    },
        artifacts = {},
        data = glob([
        "Cargo.toml",
        "src/**",
        "tests/**"
    ], exclude = [
        "**/target/**",
        "**/node_modules/**"
    ]),
        cell = "gaugewright-directory",
        crate_dir = ".",
        fixed_root = "/mnt/gaugewright-native",
        default_target_platform = "prelude//platforms:default",
    )
    native.rust_test(
        name = "rust-test-gaugewright-directory-directory_live--build",
        srcs = glob([
        "tests/directory_live.rs",
        "tests/directory_live/**",
        "tests/support/**",
        "tests/common/**"
    ]) + [],
        crate = "directory_live",
        crate_root = "tests/directory_live.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugewright-directory",
        "CARGO_PKG_VERSION": "0.0.0",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "0",
        "CARGO_PKG_VERSION_PATCH": "0",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "directory_live",
        "CARGO_BIN_EXE_gaugewright-directory": "/mnt/gaugewright-native/bin/gaugewright-directory"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory"
    ],
        deps = [
        "//third-party:axum-0_7",
        "//third-party:proptest",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:sha2",
        "//third-party:tempfile",
        "//third-party:tokio",
        "//third-party:tracing-subscriber",
        "//third-party:ureq",
        ":rust-gaugedesk-app--aff713e2",
        ":rust-gaugedesk-core",
        ":rust-gaugedesk-directory-protocol",
        ":rust-gaugedesk-store",
        ":rust-gaugewright-directory"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    native_test_run(
        name = "rust-test-gaugewright-directory-directory_live--build-run",
        test = ":rust-test-gaugewright-directory-directory_live--build",
        bins = {
        "gaugewright-directory": ":rust-bin-gaugewright-directory"
    },
        artifacts = {},
        data = glob([
        "Cargo.toml",
        "src/**",
        "tests/**"
    ], exclude = [
        "**/target/**",
        "**/node_modules/**"
    ]),
        cell = "gaugewright-directory",
        crate_dir = ".",
        fixed_root = "/mnt/gaugewright-native",
        default_target_platform = "prelude//platforms:default",
    )
    native.rust_test(
        name = "rust-test-gaugewright-directory-directory_wiring--build",
        srcs = glob([
        "tests/directory_wiring.rs",
        "tests/directory_wiring/**",
        "tests/support/**",
        "tests/common/**"
    ]) + [],
        crate = "directory_wiring",
        crate_root = "tests/directory_wiring.rs",
        edition = "2021",
        env = {
        "RUSTC_BOOTSTRAP": "1",
        "CARGO": "cargo",
        "CARGO_PKG_NAME": "gaugewright-directory",
        "CARGO_PKG_VERSION": "0.0.0",
        "CARGO_PKG_VERSION_MAJOR": "0",
        "CARGO_PKG_VERSION_MINOR": "0",
        "CARGO_PKG_VERSION_PATCH": "0",
        "CARGO_PKG_VERSION_PRE": "",
        "CARGO_CRATE_NAME": "directory_wiring",
        "CARGO_BIN_EXE_gaugewright-directory": "/mnt/gaugewright-native/bin/gaugewright-directory"
    },
        features = [],
        rustc_flags = [
        "-Zunstable-options",
        "--env-set=CARGO_MANIFEST_DIR=/mnt/gaugewright-native/gaugewright-directory"
    ],
        deps = [
        "//third-party:axum-0_7",
        "//third-party:proptest",
        "//third-party:serde",
        "//third-party:serde_json",
        "//third-party:sha2",
        "//third-party:tempfile",
        "//third-party:tokio",
        "//third-party:tracing-subscriber",
        "//third-party:ureq",
        ":rust-gaugedesk-app--aff713e2",
        ":rust-gaugedesk-core",
        ":rust-gaugedesk-directory-protocol",
        ":rust-gaugedesk-store",
        ":rust-gaugewright-directory"
    ],
        clippy_configuration = ":clippy-configuration",
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    native_test_run(
        name = "rust-test-gaugewright-directory-directory_wiring--build-run",
        test = ":rust-test-gaugewright-directory-directory_wiring--build",
        bins = {
        "gaugewright-directory": ":rust-bin-gaugewright-directory"
    },
        artifacts = {},
        data = glob([
        "Cargo.toml",
        "src/**",
        "tests/**"
    ], exclude = [
        "**/target/**",
        "**/node_modules/**"
    ]),
        cell = "gaugewright-directory",
        crate_dir = ".",
        fixed_root = "/mnt/gaugewright-native",
        default_target_platform = "prelude//platforms:default",
    )
    native_test_suite(
        name = "native-tests",
        runs = [
        ":rust-test-gaugewright-directory-lib--build-run",
        ":rust-test-gaugewright-directory-bin-gaugewright-directory--build-run",
        ":rust-test-gaugewright-directory-directory_live--build-run",
        ":rust-test-gaugewright-directory-directory_wiring--build-run"
    ],
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
    native_lint_suite(
        name = "native-lints",
        reports = [
        ":rust-bin-gaugewright-directory[clippy.txt]",
        ":rust-gaugewright-directory[clippy.txt]",
        ":rust-test-gaugewright-directory-lib--build[clippy.txt]",
        ":rust-test-gaugewright-directory-bin-gaugewright-directory--build[clippy.txt]",
        ":rust-test-gaugewright-directory-directory_live--build[clippy.txt]",
        ":rust-test-gaugewright-directory-directory_wiring--build[clippy.txt]"
    ],
        default_target_platform = "prelude//platforms:default",
        visibility = ["PUBLIC"],
    )
