#!/usr/bin/env python3
"""Render a cargo workspace's crates as native Buck2 targets (GaugeWright BUILD.md stages 5 and 6).

This file is rendered from tools/shared-checks/buckify-crates.py in the
GaugeWright repository, which owns it, by `node tools/shared-checks.mjs --write`.
It verifies itself on every run, so a local edit fails; change it there.

Cargo.toml stays the one source of truth for what a crate is and what it depends
on; this renders it into native-crates.bzl, which the root BUCK calls. `--check`
exits non-zero when the committed file is not what Cargo.toml renders to, which
is how the two are kept from drifting apart.

What differs between repositories is stated once, in the workspace's own
Cargo.toml, and nowhere else:

    [workspace.metadata.native]
    cell = "whipplescript"            # the Buck2 cell this checkout is
    checkout = "whipplescript-src"    # its repository id
    feature-checks = "feature-builds" # optional: the scripts/section.sh case
                                      # whose `cargo check -p` lines are the
                                      # bar's other configurations
    doctests = true                   # optional: run the members' doctests
                                      # natively, as `cargo test --doc` does
    wasm = [{ package = "p", default-features = false, bindgen = "bundler" }]
                                      # optional: builds of a package for
                                      # wasm32-unknown-unknown, as
                                      # `cargo build -p p --target
                                      # wasm32-unknown-unknown --release`
                                      # (`wasm-p`, the .wasm), and with
                                      # bindgen, wasm-bindgen's --target
                                      # over it (`wasm-bindgen-p`)
    ignored-tests = "a-section"       # optional: the scripts/section.sh case
                                      # whose `cargo test -p P (--test T|--bin B)
                                      # -- --ignored [filter]` lines are runs
                                      # of ignored tests the bar also makes
    dependents = ["shell"]            # optional: other workspaces here that take
                                      # this one's crates by path; the rendering
                                      # gains dependent_srcs("shell"), what
                                      # cargo reads of this workspace to build it
    open = "scripts/mirror-paths.txt" # optional: the file listing what the
                                      # curated public mirror publishes
                                      # (GaugeWright DR-0137); see "Open and
                                      # closed" below

Open and closed (BUILD.md stage 6). A repository that publishes a curated
mirror names the file its publisher reads the published paths from: paths
separated by whitespace, `#` to the end of a line a comment, a directory
covering everything beneath it. A first-party crate is OPEN when its Cargo.toml
is published and CLOSED otherwise, and the rendering makes Buck2 refuse an open
target that depends on a closed one. That cannot be said with `visibility` on
the targets themselves: Buck2 never checks visibility between two targets of
one package, and every target here is in the root package. So every edge INTO
a closed library goes through an alias in a package of its own,
`native-closed/` (`<dir>/native-closed/` for a second workspace), whose BUCK
file this renders beside native-crates.bzl. The alias is visible only to the
closed targets, and the closed library itself only to that package, so an
open library, binary, test or doctest that takes a closed crate fails the
build's analysis, naming both. Open targets stay PUBLIC. Without `open`
nothing is closed and the rendering is what it was.

The targets live in the ROOT package because the crates reach outside their own
directories at compile time -- include_str!("../../../examples/...") and a build
script reading a sibling tree -- and Buck2 lets a package declare only files
beneath it. From the root, every file sits at its real path, so every relative
include resolves exactly as it does under cargo.

First-party is every path package the workspace builds, which is more than its
members: a crate taken by `path` from a vendored peer (a `platform/` submodule)
is compiled from this checkout as cargo compiles it, while only the members are
linted, tested and given binaries, as `--workspace` does.

Third-party crates are //third-party:<name>, generated by reindeer from
third-party/Cargo.toml. The build has the workspace's default features, which is
what `cargo build --workspace` builds, resolved for Linux and macOS; where the
two resolve differently the difference is a select().

A second workspace the repository keeps apart, with a lockfile of its own, is
rendered with `--workspace <dir>`. Its targets live in the root package too, for
the same reason, and their names carry the directory's name where they would
meet the main workspace's; what is its own is the cargo side. Its Cargo.toml
carries its [workspace.metadata.native] and excludes <dir>/third-party, its
graph's own, and the rendering is <dir>/native-crates.bzl and
<dir>/native-bar.json, which the root BUCK loads beside the main one.
"""
import hashlib, json, os, re, subprocess, sys
from pathlib import Path

SOURCE_DIGEST = "5d445d60044c823afedbdcbe577aed08f19e1c9805c73ceae1da896089c6c347"
PLACEHOLDER = "__EXPECTED_DIGEST__"

ROOT = Path(__file__).resolve().parent.parent
PKG = next((sys.argv[i + 1] for i, a in enumerate(sys.argv[:-1]) if a == "--workspace"), "").strip("/")
# The cargo workspace rendered: the repository's own, or with --workspace, one
# it keeps apart.
WS = ROOT / PKG if PKG else ROOT
TP_DIR = f"{PKG}/third-party" if PKG else "third-party"
# What a second workspace's target names end with where they would otherwise
# be the main workspace's: its suites and clippy configurations.
SUFFIX = "-" + Path(PKG).name if PKG else ""
RUN = "scripts/buckify-crates.py" + (f" --workspace {PKG}" if PKG else "")
OUT = WS / "native-crates.bzl"
INDEX = WS / "native-bar.json"
THIRD_PARTY = WS / "third-party/Cargo.toml"
# The package every edge into a closed crate goes through (see "Open and closed").
CLOSED_PKG = f"{PKG}/native-closed" if PKG else "native-closed"
CLOSED_BUCK = ROOT / CLOSED_PKG / "BUCK"
PLATFORM = "prelude//platforms:default"
WASM_PLATFORM = "gaugewright//tools/buck:wasm32"

def variant_platform(config, package):
    """A bare target keeps the architecture its dependencies were resolved for.

    Proc macros execute on the compiler host even in a WASM configuration.
    Ordinary WASM libraries must also build for WASM when selected directly,
    rather than depending on their module wrapper to supply a transition.
    """
    proc_macro = any("proc-macro" in target["kind"] for target in package["targets"])
    host_unit = package["name"] in config.get("host_packages", set())
    return WASM_PLATFORM if config.get("wasm") and not proc_macro and not host_unit else PLATFORM

def platform_variant_key(key, platform):
    """Do not reuse a host target for identical WASM features/dependencies.

    Host keys stay stable; WASM target identity includes its architecture.
    """
    return json.dumps([platform, key]) if platform != PLATFORM else key
INCLUDE = re.compile(r'include(?:_str|_bytes)?!\(\s*"([^"]+)"\s*\)|#\[path\s*=\s*"([^"]+)"\]')
# The hosts a native build runs on, as the prelude's OS constraints name them.
# A workspace resolves the same on both almost everywhere; where it does not,
# the rendering says so with a select() rather than being one host's answer.
HOSTS = [("linux", "x86_64-unknown-linux-gnu"), ("macos", "aarch64-apple-darwin")]

def verify_rendered_copy():
    """Fail if this rendered copy has drifted from the source that owns it."""
    if SOURCE_DIGEST == PLACEHOLDER:
        return
    body = Path(__file__).read_text().replace(
        f'SOURCE_DIGEST = "{SOURCE_DIGEST}"', f'SOURCE_DIGEST = "{PLACEHOLDER}"', 1)
    if hashlib.sha256(body.encode()).hexdigest() != SOURCE_DIGEST:
        sys.exit("scripts/buckify-crates.py has been edited locally. It is generated from "
                 "tools/shared-checks/buckify-crates.py in the GaugeWright repository; change it "
                 "there and re-render with `node tools/shared-checks.mjs --write`.")

def metadata(*extra):
    out = subprocess.run(["cargo", "metadata", "--format-version", "1", "--locked", *extra],
                         cwd=WS, check=True, capture_output=True, text=True).stdout
    return json.loads(out)

def dependent_srcs(dependents):
    """`def dependent_srcs(workspace)` for native-crates.bzl: for each workspace
    in the repository that takes this one's crates by path, what cargo reads of
    this workspace to build it. That is every crate outside the dependent's own
    directory that its resolve compiles, as that crate's library target here
    reads it -- its code and what the code embeds, not its tests, examples or
    benches, which cargo does not build for a dependent -- and the workspace
    manifest those crates inherit from. A section that builds the dependent is
    then keyed on this and its own tree rather than on the whole workspace, so a
    change it cannot see does not rerun it. Every local package in the resolve
    counts, whatever the target, so a platform-only path dependency is read too.
    """
    if not dependents:
        return []
    out = ["", "def dependent_srcs(workspace):",
           '    """What a dependent workspace reads of this one (scripts/buckify-crates.py)."""']
    for dep in dependents:
        dep_dir = (ROOT / dep).resolve()
        dm = json.loads(subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--locked", "--manifest-path", str(dep_dir / "Cargo.toml")],
            cwd=ROOT, check=True, capture_output=True, text=True).stdout)
        used = {Path(p["manifest_path"]).parent: p for p in dm["packages"]
                if p["source"] is None and not Path(p["manifest_path"]).parent.is_relative_to(dep_dir)
                and Path(p["manifest_path"]).parent.is_relative_to(ROOT)}
        # A target a manifest declares by name -- [[example]], [[test]] and the
        # like -- must exist for cargo to parse that manifest at all, even for a
        # crate it takes only as a dependency and builds none of them for. Its
        # entry file is read; the rest of it is not.
        declared = set()
        for d, p in used.items():
            names = set(re.findall(r'^\[\[(?:example|test|bench|bin)\]\]\s*\nname\s*=\s*"([^"]+)"',
                                   (d / "Cargo.toml").read_text(), re.M))
            declared |= {str(Path(t["src_path"]).relative_to(ROOT)) for t in p["targets"] if t["name"] in names}
        exprs = [target_srcs(d, "code") for d in sorted(used)] + [star(sorted(declared | {str((WS / "Cargo.toml").relative_to(ROOT))}))]
        out += [f'    if workspace == "{dep}":', "        return " + " + ".join(exprs)]
    out.append('    fail("buckify-crates: no dependent workspace " + workspace + "; name it in [workspace.metadata.native] dependents")')
    return out

def native_config(m):
    """[workspace.metadata.native] from the workspace's Cargo.toml."""
    native = (m.get("metadata") or {}).get("native") or {}
    missing = [k for k in ("cell", "checkout") if not native.get(k)]
    if missing:
        sys.exit(f"buckify-crates: [workspace.metadata.native] in Cargo.toml must name {' and '.join(missing)}")
    return native

def open_paths(listing):
    """The paths a mirror's path list publishes: whitespace-separated, `#`
    starting a comment, without leading `./` or trailing `/`."""
    paths = set()
    for line in listing.splitlines():
        for word in line.split("#", 1)[0].split():
            word = word.strip("/")
            while word.startswith("./"):
                word = word[2:]
            paths.add(word or ".")
    return paths

def is_open(path, published):
    """Whether a repository-relative path is published: listed, or beneath a
    listed directory."""
    return "." in published or any(path == p or path.startswith(p + "/") for p in published)

def closed_crates(config, manifest_dirs):
    """{package} of the first-party crates the mirror does not publish, given
    {package: repository-relative crate directory}. Empty without `open`."""
    listing = config.get("open")
    if not listing:
        return set()
    if not (ROOT / listing).is_file():
        sys.exit(f"buckify-crates: [workspace.metadata.native] open names {listing}, which does not exist")
    published = open_paths((ROOT / listing).read_text())
    return {pkg for pkg, rel in manifest_dirs.items() if not is_open(join(rel, "Cargo.toml"), published)}

def closed_package(aliases, consumers):
    """The BUCK file of the closed package: an alias of each closed library
    something takes, under the library's own name, visible only to the closed
    targets."""
    lines = [
        f"# @generated by {RUN} from the workspace's Cargo.toml files and the",
        "# mirror's published paths ([workspace.metadata.native] open). Do not edit.",
        "#",
        "# Every edge into a closed crate comes through here, because Buck2 never checks",
        "# visibility between two targets of one package and every native target is in",
        "# the root package. An alias is visible only to the closed targets, so an open",
        "# target that takes a closed crate fails analysis (GaugeWright BUILD.md stage 6).",
    ]
    visible = star(sorted(f"//:{n}" for n in consumers))
    for name in sorted(aliases):
        lines += [
            "",
            "alias(",
            f'    name = "{name}",',
            f'    actual = "//:{name}",',
            f'    default_target_platform = "{PLATFORM}",',
            f"    visibility = {visible},",
            ")",
        ]
    return "\n".join(lines) + "\n"

def join(rel, path):
    """A repository-relative path under a crate directory, which is `.` for a
    package at the root."""
    return path if rel == "." else f"{rel}/{path}"

def third_party_names():
    """The names third-party/Cargo.toml gives each (package, version).

    Read through cargo rather than a TOML parser, so the script needs nothing
    newer than the Python every gate host has (Apple's is 3.9).
    """
    out = subprocess.run(["cargo", "metadata", "--format-version", "1", "--no-deps",
                          "--manifest-path", str(THIRD_PARTY)],
                         check=True, capture_output=True, text=True).stdout
    names = {}
    for d in json.loads(out)["packages"][0]["dependencies"]:
        names[(d["name"], d["req"].lstrip("="))] = d.get("rename") or d["name"]
    return names

def referenced_files(roots):
    """Every file the Rust files in roots embed or `#[path]` in, followed through
    the Rust files found that way. Repository-relative paths.

    The path the source names, not whether it exists on disk: whether it does is
    the compiler's question, and asking the filesystem would make this output
    depend on files the check does not declare (it runs sandboxed). Asked of git
    instead, which answers the same inside the sandbox: a path nothing tracks is
    either no file at all -- the text of a test fixture that happens to spell an
    include -- or one only a build makes, and in neither case a source.
    """
    found, queue, seen = set(), list(roots), set()
    while queue:
        rs = queue.pop()
        if rs in seen or not rs.exists():
            continue
        seen.add(rs)
        for m in INCLUDE.finditer(rs.read_text(errors="replace")):
            target = Path(os.path.normpath(rs.parent / (m.group(1) or m.group(2))))
            try:
                rel = str(target.relative_to(ROOT))
            except ValueError:
                continue
            if rel in tracked():
                found.add(rel)
            if target.suffix == ".rs":
                queue.append(target)
    return found

_TRACKED = None

def tracked():
    """Every tracked path, from git: the same list inside the read sandbox as
    outside it, where the filesystem shows only what a section declares. A
    submodule's files are listed as its own, so a vendored peer is seen too."""
    global _TRACKED
    if _TRACKED is None:
        out = subprocess.run(["git", "ls-files", "-z", "--recurse-submodules"], cwd=ROOT, check=True, capture_output=True).stdout
        _TRACKED = set(out.decode().split("\0")) - {""}
    return _TRACKED

def tracked_dir(path):
    prefix = path.rstrip("/") + "/"
    return any(t.startswith(prefix) for t in tracked())

def subpackages():
    """Directories below the root that are Buck2 packages of their own: a vendored
    peer that carries its BUCK file is one. A glob from the root package stops
    at such a directory and matches nothing inside it, so what a target reads
    there is named file by file instead -- which Buck2 allows the root package
    only when the cell's .buckconfig lists it in project.package_boundary_exceptions."""
    return sorted({str(Path(t).parent) for t in tracked()
                   if Path(t).name in ("BUCK", "BUCK.v2") and str(Path(t).parent) != "."})

def in_subpackage(pattern):
    base = pattern[:-3] if pattern.endswith("/**") else pattern
    return any(base == d or base.startswith(d + "/") for d in subpackages())

def expand(pattern):
    """The tracked files a `dir/**` or single-file pattern names."""
    if pattern.endswith("/**"):
        prefix = pattern[:-2]
        return {t for t in tracked() if t.startswith(prefix)}
    return {pattern} & tracked()

def data_expr(patterns):
    """A test run's data: the declared trees, less build output, named file by
    file where they lie inside a subpackage."""
    inside = [p for p in patterns if in_subpackage(p)]
    outside = [p for p in patterns if not in_subpackage(p)]
    text = f"glob({star(outside)}, exclude = {star(['**/target/**', '**/node_modules/**'])})"
    if inside:
        text += " + " + files_expr(inside)[: -len(" + []")]
    return text

def files_expr(patterns, exclude=(), extra=()):
    """A srcs expression: a glob where a glob reaches, and the files themselves
    where the patterns lie inside a subpackage, where it would not."""
    inside = [p for p in patterns if in_subpackage(p)]
    outside = [p for p in patterns if not in_subpackage(p)]
    parts = []
    if outside:
        ex = [x for x in exclude if not in_subpackage(x)]
        parts.append(f"glob({star(outside)}{', exclude = ' + star(ex) if ex else ''})")
    if inside:
        dropped = set().union(*(expand(x) for x in exclude)) if exclude else set()
        named = set().union(*(expand(p) for p in inside)) - dropped
        named = {n for n in named if "/target/" not in f"/{n}" and "/node_modules/" not in f"/{n}"}
        parts.append(star(sorted(named)))
    parts.append(star(list(extra)))
    return " + ".join(parts)

# The directories of every first-party package, repository-relative; set in
# main() before anything reads it. A package's own files stop where another's
# begin, which matters only for a package at the root.
PACKAGE_DIRS = []

def own_rust_files(crate_dir, skip=("target",)):
    """The crate's Rust files: not those of a package nested inside it, and not
    build output."""
    rel = crate_dir.relative_to(ROOT)
    nested = [ROOT / d for d in PACKAGE_DIRS if d != "." and Path(d) != rel and (ROOT / d).is_relative_to(crate_dir)]
    for rs in crate_dir.rglob("*.rs"):
        parts = rs.relative_to(crate_dir).parts
        if any(s in parts for s in skip) or "node_modules" in parts:
            continue
        if any(rs.is_relative_to(n) for n in nested):
            continue
        yield rs

RUNTIME_REACH = re.compile(r'"((?:\.\./)+)([^"\\\s]*)"')

def runtime_reach(crate_dir):
    """What a crate's code reaches by relative path at run time, as test data
    patterns: the tracked file a path names, or the tree of the tracked
    directory it names; where the path is finished at run time --
    "../../examples/{name}.whip" -- the deepest tracked directory it does name.
    Read from its sources, resolved both from the file and from the crate (a
    CARGO_MANIFEST_DIR join is relative to the crate).

    A miss fails loudly, since the test run's mount holds only what is
    declared. A surplus is paid on every change to it: until 2026-09-28 any
    such path declared its whole top-level directory, so 53 of whipplescript-
    src's test runs declared all of spec/ to read seven files in it, and the
    71% of its pull requests that touch spec/ reran them.
    """
    own = crate_dir.relative_to(ROOT)
    packages = [Path(d) for d in PACKAGE_DIRS if d != "."]
    found = set()
    for rs in own_rust_files(crate_dir):
        for m in RUNTIME_REACH.finditer(rs.read_text(errors="replace")):
            precise, broad = set(), set()
            for base in (rs.parent, crate_dir):
                try:
                    rel = Path(os.path.normpath(base / (m.group(1) + m.group(2)))).relative_to(ROOT)
                except ValueError:
                    continue
                if not rel.parts or rel.parts[0] in ("target", ".git"):
                    continue
                inside = next((p for p in packages if rel == p or rel.is_relative_to(p)), None)
                if inside == own:
                    continue  # the crate's own tree is declared already
                if inside is None and any(p.parts[0] == rel.parts[0] for p in packages):
                    # Under a directory that holds packages, such as crates/,
                    # but in none of them: what is named there is not a
                    # package, and the directory is not the crate's to read.
                    continue
                if str(rel) in tracked():
                    precise.add(str(rel))
                elif tracked_dir(str(rel)):
                    precise.add(str(rel) + "/**")
                else:
                    # A path finished at run time: the deepest directory it
                    # names that holds tracked files.
                    for d in rel.parents:
                        if str(d) != "." and tracked_dir(str(d)):
                            broad.add(str(d) + "/**")
                            break
            found |= precise or broad
    return sorted(found)

def target_srcs(crate_dir, kind, name=None):
    """What one target reads, as tightly as cargo would rebuild it.

    A library or binary: the crate minus its tests, examples and benches (its
    own non-Rust files, such as the store's SQL migrations, stay in). An
    integration test or example: its own file and directory, and the shared
    helper directories tests use. Plus everything any of those embeds or
    `#[path]`s in, wherever it lives. Editing one test file therefore rebuilds
    that test, not the library every other target depends on.

    A package at the root of the workspace is the exception: its directory is
    the whole workspace, so its library is its src/ and what that embeds.
    """
    rel = str(crate_dir.relative_to(ROOT))
    if kind == "code" and crate_dir == WS:
        patterns, exclude = [join(rel, "src/**")], []
        roots = [f for f in own_rust_files(crate_dir / "src")]
    elif kind == "code":
        patterns = [f"{rel}/**"]
        exclude = [f"{rel}/{d}/**" for d in ("tests", "examples", "benches", "target")]
        roots = [f for f in own_rust_files(crate_dir)
                 if not any(f.is_relative_to(crate_dir / d) for d in ("tests", "examples", "benches", "target"))]
    else:
        base = crate_dir / kind
        patterns = [join(rel, f"{kind}/{name}.rs"), join(rel, f"{kind}/{name}/**")]
        if kind == "tests":
            patterns += [join(rel, "tests/support/**"), join(rel, "tests/common/**")]
        exclude = []
        roots = [base / f"{name}.rs"] + [f for d in (base / name, base / "support", base / "common") if d.is_dir() for f in d.rglob("*.rs")]
    def is_covered(path):
        for pat in patterns:
            if pat.endswith("/**") and path.startswith(pat[:-2]) and not any(path.startswith(x[:-2]) for x in exclude):
                return True
            if path == pat:
                return True
        return False
    extra = sorted(p for p in referenced_files(roots) if not is_covered(p))
    return files_expr(patterns, exclude, extra)

def patch_sections():
    """The workspace's [patch.*] tables, verbatim. Cargo applies a patch only from
    the top-level workspace, so the third-party manifest must carry it to resolve
    the same packages."""
    text = (WS / "Cargo.toml").read_text()
    return [m.group(0).rstrip("\n") for m in re.finditer(r'^\[patch\.[^\]]+\]\n(?:[^\[\n].*\n|\n)*', text, re.M)]

_CFGS = {}

def target_cfgs(triple):
    """(names, key=value pairs) rustc says hold for a target."""
    if triple not in _CFGS:
        out = subprocess.run(["rustc", "--print", "cfg", "--target", triple], cwd=ROOT,
                             check=True, capture_output=True, text=True).stdout
        names, pairs = set(), set()
        for line in out.splitlines():
            if "=" in line:
                k, v = line.split("=", 1)
                pairs.add((k, v.strip('"')))
            else:
                names.add(line)
        _CFGS[triple] = (names, pairs)
    return _CFGS[triple]

def cfg_holds(expr, triple):
    """Whether a dependency's `target` -- a cfg(...) or a bare triple -- holds for triple."""
    if not expr.startswith("cfg("):
        return expr == triple
    names, pairs = target_cfgs(triple)
    tokens = re.findall(r'[A-Za-z_][A-Za-z0-9_]*|"[^"]*"|[(),=]', expr[4:-1])
    pos = 0
    def parse():
        nonlocal pos
        tok = tokens[pos]
        pos += 1
        if tok in ("all", "any", "not") and pos < len(tokens) and tokens[pos] == "(":
            pos += 1
            args = []
            while tokens[pos] != ")":
                args.append(parse())
                if tokens[pos] == ",":
                    pos += 1
            pos += 1
            return all(args) if tok == "all" else any(args) if tok == "any" else not args[0]
        if pos < len(tokens) and tokens[pos] == "=":
            val = tokens[pos + 1].strip('"')
            pos += 2
            return (tok, val) in pairs
        return tok in names
    return parse()

WASM_CFG = "cfg(target_arch = \"wasm32\")"
HOST_CFG = "cfg(not(target_arch = \"wasm32\"))"

def render_third_party(cell, local, wasm_builds=()):
    """third-party/Cargo.toml: every external crate a first-party package names,
    pinned at the version the workspace lockfile resolves, with the union of the
    features they ask for. Resolved with every feature on, so an optional
    dependency (custodian's cryptoki, behind `pkcs11`) is pinned too. A package
    wanted at two versions keeps its name at the newer one and takes
    `<name>-<maj>_<min>` at the older, which reindeer turns into a second public
    target. A dependency the lockfile resolves for no one -- an optional one no
    feature turns on, a non-member's dev-dependency -- is not wanted.
    """
    m = metadata("--all-features")
    pkgs = {p["id"]: p for p in m["packages"]}
    nodes = {n["id"]: n for n in m["resolve"]["nodes"]}
    want = {}
    for pid in sorted(local, key=lambda i: (pkgs[i]["name"], i)):
        p = pkgs[pid]
        if pid not in nodes:
            continue
        resolved = {}
        for d in nodes[pid]["deps"]:
            resolved.setdefault(pkgs[d["pkg"]]["name"], set()).add(pkgs[d["pkg"]]["version"])
        for d in p["dependencies"]:
            if d.get("path"):
                continue
            versions = resolved.get(d["name"], set())
            if not versions:
                continue
            # The leading components the requirement names, compared as
            # components: "1" is not a prefix of "10.0.0".
            wanted = d["req"].lstrip("^=~ ").split(".")[:2]
            # Each version the declaration resolved to takes its features: two
            # versions of one crate are two crates, and a feature one of them
            # has is not the other's to be asked for.
            for v in {v for v in versions if v.split(".")[:len(wanted)] == wanted} or versions:
                w = want.setdefault(d["name"], {}).setdefault(v, {"features": set(), "default": False, "targets": set()})
                w["features"] |= set(d["features"])
                w["default"] |= d["uses_default_features"]
                if d.get("target"):
                    w["targets"].add(d["target"])
                else:
                    w["targets"].add(None)

    # A wasm build's direct third-party dependencies, with the features its
    # own crates ask for on that target: cargo resolves a build for one target,
    # so the host's features are not the wasm build's. They are listed under
    # the wasm cfg and the host's under its negation, which reindeer resolves
    # per platform as cargo would. Build dependencies are the host's, as a
    # build script runs on the host.
    wasm_want = {}
    for resolution in wasm_builds:
        for pkg_name, (_, _, tp_by_os) in resolution.items():
            p = next(pkgs[i] for i in local if pkgs[i]["name"] == pkg_name)
            used = set().union(*tp_by_os.values())
            for d in p["dependencies"]:
                if d.get("path") or d["kind"] not in (None, "normal"):
                    continue
                if d.get("target") and not cfg_holds(d["target"], WASM[1]):
                    continue
                for (n, v) in used:
                    if n != d["name"]:
                        continue
                    w = wasm_want.setdefault(n, {}).setdefault(v, {"features": set(), "default": False, "targets": set()})
                    w["features"] |= set(d["features"])
                    w["default"] |= d["uses_default_features"]

    def key(v):
        return [int(x) for x in v.split("-")[0].split(".")]

    def renamed(name, v):
        """The name a version is listed under: the newest wanted anywhere keeps
        the crate's name, an older one takes `<name>-<maj>_<min>`."""
        newest = max(set(want.get(name, {})) | set(wasm_want.get(name, {})), key=key)
        return None if v == newest else f"{name}-{v.split('.')[0]}_{v.split('.')[1]}"

    def spec(name, version, w, rename=None):
        parts = ([f'package = "{name}"'] if rename else []) + [f'version = "={version}"']
        if not w["default"]:
            parts.append("default-features = false")
        if w["features"]:
            parts.append("features = [" + ", ".join(f'"{f}"' for f in sorted(w["features"])) + "]")
        return f'{rename or name} = {{ {", ".join(parts)} }}'

    lines = [
        f"# @generated by {RUN} from the workspace's Cargo.toml files.",
        "# Reindeer's input for the native third-party targets (GaugeWright BUILD.md",
        "# stage 5), not a crate: the workspace excludes it. After re-rendering, copy",
        f"# ../Cargo.lock here and run `reindeer --third-party-dir {TP_DIR} buckify`.",
        "[package]", f'name = "{cell}-third-party"', 'version = "0.0.0"', 'edition = "2021"',
        "publish = false", "", "[lib]", 'path = "top.rs"', "", "[dependencies]",
    ]
    by_target = {}
    for name in sorted(want):
        vs = sorted(want[name], key=key)
        # A version any member takes unconditionally is a plain dependency;
        # one taken only under a cfg is listed under each of them. With a wasm
        # build, "unconditionally" means on every host, and a cfg the wasm
        # target satisfies is the wasm build's to answer.
        targets = set().union(*(want[name][v]["targets"] for v in vs))
        out = [spec(name, v, want[name][v], rename=renamed(name, v)) for v in reversed(vs)]
        out = [out[0]] + sorted(out[1:], key=lambda line: vs.index(re.search(r'version = "=([^"]+)"', line).group(1)))
        if wasm_builds:
            # A cfg the wasm target satisfies is the wasm build's to answer --
            # unless no wasm build takes that version, in which case it stays
            # where a member declared it, so the lockfile still pins it.
            covered = set(wasm_want.get(name, {}))
            for v in reversed(vs):
                line = spec(name, v, want[name][v], rename=renamed(name, v))
                for t in sorted(want[name][v]["targets"], key=lambda t: t or ""):
                    table = HOST_CFG if t is None else t if (not cfg_holds(t, WASM[1]) or v not in covered) else None
                    # Once per table: an unconditional declaration and one under
                    # the host's own cfg land in the same one.
                    if table and line not in by_target.setdefault(table, []):
                        by_target[table].append(line)
        elif None not in targets:
            for t in sorted(targets):
                by_target.setdefault(t, []).extend(out)
        else:
            lines += out
    if wasm_builds:
        for name in sorted(wasm_want):
            for v in sorted(wasm_want[name], key=key, reverse=True):
                by_target.setdefault(WASM_CFG, []).append(spec(name, v, wasm_want[name][v], rename=renamed(name, v)))
    for t in sorted(by_target):
        lines += ["", f"[target.'{t}'.dependencies]"] + by_target[t]
    for patch in patch_sections():
        lines += ["", patch]
    return "\n".join(lines) + "\n"

def profile_opt_levels():
    """{crate: opt-level} from Cargo.toml's [profile.dev.package.<crate>] tables."""
    text = (WS / "Cargo.toml").read_text()
    out = {}
    for m in re.finditer(r'^\[profile\.dev\.package\.([A-Za-z0-9_-]+)\]\n((?:[^\[\n].*\n)*)', text, re.M):
        lvl = re.search(r'^opt-level\s*=\s*"?(\w+)"?', m.group(2), re.M)
        if lvl:
            out[m.group(1)] = lvl.group(1)
    return out

def fixup_opt_levels():
    """{crate: opt-level} the generated third-party targets pass to rustc.

    Read from third-party/BUCK, which the native-crates section declares, rather
    than from the fixups reindeer rendered it from, which a sandboxed section in
    the root package cannot declare. A crate appears once per version.
    """
    out = {}
    text = (WS / "third-party/BUCK").read_text()
    for block in text.split("\ncargo.rust_library(")[1:]:
        name = re.search(r'name = "([^"]+)"', block)
        flag = re.search(r'"-Copt-level=(\w+)"', block.split("\n)\n", 1)[0])
        if name and flag:
            out[re.sub(r"-\d+(\.\d+)*(-[^-]+)?$", "", name.group(1))] = flag.group(1)
    return out

def lock_packages(path):
    """(name, version, source, checksum) of every external package a Cargo.lock pins.

    Parsed by hand rather than with tomllib, which the Python on the Mac gate
    host (Apple's 3.9) does not have; a lockfile's [[package]] blocks are flat.
    """
    found, cur = set(), {}
    for line in list(path.read_text().splitlines()) + ["[[package]]"]:
        if line == "[[package]]":
            if cur.get("source", "").startswith(('"registry+', '"git+')):
                found.add((cur["name"], cur["version"], cur["source"], cur.get("checksum", "")))
            cur = {}
        elif " = " in line:
            k, v = line.split(" = ", 1)
            cur[k] = v
    return found

def verify_git_materialization(lock_path, buck_path):
    """The native fetch must use each exact commit selected by Cargo, not a ref."""
    expected = set()
    for _, _, source, _ in lock_packages(lock_path):
        source = json.loads(source)
        if source.startswith("git+"):
            repository, separator, revision = source[4:].rpartition("#")
            if not separator or not revision:
                sys.exit("native git source has no exact locked revision")
            expected.add((repository.split("?", 1)[0], revision))
    actual = set()
    for body in re.findall(r"^git_fetch\(\n(.*?)^\)", buck_path.read_text(), re.M | re.S):
        fields = {}
        for name in ("repo", "rev"):
            match = re.search(r'^\s+' + name + r' = ("(?:[^"\\]|\\.)*"),$', body, re.M)
            if not match:
                sys.exit("native git_fetch has no literal repository/revision")
            fields[name] = json.loads(match.group(1))
        actual.add((fields["repo"], fields["rev"]))
    if expected != actual:
        sys.exit("third-party/BUCK git_fetch differs from exact Cargo.lock sources; "
                 "copy Cargo.lock into third-party/ and re-run reindeer")


def star(value):
    return json.dumps(value, indent=4).replace("\n", "\n    ")

# ---- configurations: what the bar actually compiles --------------------------

def bar_configurations(section):
    """Every cargo configuration the bar compiles Rust in, read from the bar.

    `build` is `cargo build --workspace`; `test` is what nextest and
    `clippy --workspace --all-targets` compile (dev-dependencies on). The rest are
    the `cargo check -p ...` lines of the named section.sh case, so the list of
    variants has one owner: the bar.
    """
    configs = {
        "build": {"args": ["--workspace"], "edges": "normal,build", "all_targets": set()},
        "test": {"args": ["--workspace"], "edges": "normal,build,dev", "all_targets": "*"},
    }
    if not section:
        return configs
    text = (ROOT / "scripts/section.sh").read_text()
    block = text[text.index(f"  {section})"):]
    block = block[: block.index(";;")]
    for line in block.splitlines():
        m = re.search(r"cargo check (-p \S+.*)$", line.strip())
        if not m:
            continue
        args = m.group(1).split()
        pkg = args[1]
        all_targets = "--all-targets" in args
        args = [a for a in args if a != "--all-targets"]
        name = "check-" + "-".join(a.lstrip("-") for a in args[1:])
        configs[name] = {
            "args": args,
            "edges": "normal,build,dev" if all_targets else "normal,build",
            "all_targets": {pkg} if all_targets else set(),
            "check_root": pkg,
        }
    return configs

IGNORED_LINE = re.compile(r"cargo test -p (\S+) --(test|bin) (\S+) -- --ignored ?(\S*)")

def ignored_runs(section):
    """{(package, "test"|"bin", name): filter} from the named section.sh case: the
    runs of ignored tests the bar makes beside its ordinary ones. Read from the
    `cargo test` lines, which name the binary where nextest's filter does not."""
    if not section:
        return {}
    text = (ROOT / "scripts/section.sh").read_text()
    block = text[text.index(f"  {section})"):]
    block = block[: block.index(";;")]
    return {(m.group(1), m.group(2), m.group(3)): m.group(4) for m in IGNORED_LINE.finditer(block)}

TREE_LINE = re.compile(r"^(\d+)(\S+) v(\S+)( \(([^)]*)\))?\|(.*?)( \(\*\))?$")

def resolve_for(config, members, triple):
    """{package: (features, first-party deps, third-party deps)} for one configuration on one host."""
    out = subprocess.run(
        ["cargo", "tree", "--locked", *config["args"], "-e", config["edges"],
         "--prefix", "depth", "--format", "{p}|{f}", "--target", triple],
        cwd=WS, check=True, capture_output=True, text=True).stdout
    resolved, stack = {}, []
    for raw in out.splitlines():
        m = TREE_LINE.match(raw)
        if not m:
            continue
        depth, name, version = int(m.group(1)), m.group(2), m.group(3)
        features = set(filter(None, m.group(6).split(",")))
        del stack[depth:]
        if stack:
            parent = stack[-1]
            if parent in members:
                entry = resolved.setdefault(parent, [None, set(), set()])
                if name in members:
                    entry[1].add(name)
                else:
                    entry[2].add((name, version))
        if name in members:
            entry = resolved.setdefault(name, [None, set(), set()])
            entry[0] = features if entry[0] is None else entry[0] | features
        stack.append(name)
    return {k: (v[0] or set(), v[1], v[2]) for k, v in resolved.items()}

WASM = ("wasm", "wasm32-unknown-unknown")

def classify_wasm_units(graph, packages, members, include_domains=False):
    """Retain exact first-party host/WASM units and edges without compiling.

    A package may occur in both domains with identical features. Different
    feature sets or multiple profiles in a domain remain unsupported; target-
    conditional host dependencies remain refused rather than guessed portable.
    """
    if graph.get("version") != 1:
        sys.exit("buckify-crates: unsupported Cargo unit-graph version")
    units = graph["units"]
    by_id = {p["id"]: p for p in packages}
    local_ids = {}
    for name in members:
        admitted = [p["id"] for p in packages if p["name"] == name and p["source"] is None]
        if len(admitted) != 1:
            sys.exit(f"buckify-crates: ambiguous first-party package identity for {name}")
        local_ids[name] = admitted[0]
    domains, selected = {}, {}
    def library(unit):
        return unit["mode"] == "build" and bool(set(unit["target"]["kind"]) & {"lib", "rlib", "cdylib", "proc-macro"})
    def identity(unit):
        package = by_id.get(unit["pkg_id"])
        if package is None:
            sys.exit(f"buckify-crates: Cargo unit {unit['pkg_id']} is absent from metadata")
        if package["name"] in local_ids and package["id"] != local_ids[package["name"]]:
            sys.exit(f"buckify-crates: conflicting first-party package identity for {package['name']}")
        platform = unit["platform"]
        if platform not in (None, WASM[1]):
            sys.exit(f"buckify-crates: unsupported unit platform {platform} for {package['name']}")
        return package, "host" if platform is None else "wasm"
    for i, unit in enumerate(units):
        if not library(unit):
            continue
        package, domain = identity(unit)
        name = package["name"]
        if name not in members:
            continue
        features = tuple(sorted(unit["features"]))
        entry = domains.setdefault(name, {}).setdefault(domain, {"features": set(), "profiles": set()})
        entry["features"].add(features)
        entry["profiles"].add(json.dumps(unit.get("profile"), sort_keys=True))
        selected.setdefault((name, domain), []).append(i)
    for name, records in domains.items():
        feature_sets = set().union(*(r["features"] for r in records.values()))
        if len(feature_sets) != 1 or any(len(r["profiles"]) != 1 for r in records.values()):
            sys.exit(f"buckify-crates: {name} has ambiguous host/WASM feature sets or profiles; separate unsupported unit rendering is required")
        if "host" in records:
            package = next(p for p in packages if p["name"] == name and p["source"] is None)
            if any(d.get("target") and d["kind"] != "dev" for d in package["dependencies"]):
                sys.exit(f"buckify-crates: host-side {name} has target-specific dependencies; portable host-domain rendering is not established")
    records = {}
    def dependencies(indices, expected_domain=None):
        first, third = set(), set()
        for i in indices:
            unit = units[i]
            if not library(unit):
                sys.exit("buckify-crates: unsupported non-library dependency in Cargo domain")
            package, domain = identity(unit)
            macro = "proc-macro" in unit["target"]["kind"]
            if expected_domain and domain != ("host" if macro else expected_domain):
                sys.exit("buckify-crates: Cargo dependency crosses an unsupported unit domain")
            if package["name"] in members:
                first.add((package["name"], domain))
            else:
                third.add((package["name"], package["version"]))
        return first, third
    for (name, domain), indices in selected.items():
        answers = []
        for i in indices:
            normal, build = [], []
            for dep in units[i]["dependencies"]:
                j = dep["index"]
                if units[j]["mode"] == "run-custom-build":
                    scripts = units[j]["dependencies"]
                    if len(scripts) != 1 or units[scripts[0]["index"]]["target"]["kind"] != ["custom-build"] or units[j]["pkg_id"] != units[i]["pkg_id"] or units[scripts[0]["index"]]["pkg_id"] != units[i]["pkg_id"]:
                        sys.exit("buckify-crates: unsupported Cargo build-script dependency shape")
                    program = units[scripts[0]["index"]]
                    build.extend(d["index"] for d in program["dependencies"])
                else:
                    normal.append(j)
            nf, nt = dependencies(normal, domain)
            bf, bt = dependencies(build, "host")
            answers.append((nf, nt, bf, bt))
        if any(answer != answers[0] for answer in answers[1:]):
            sys.exit(f"buckify-crates: {name} has multiple dependency graphs in one domain")
        nf, nt, bf, bt = answers[0]
        records[(name, domain)] = {"features": set(next(iter(domains[name][domain]["features"]))),
                                  "normal_fp": nf, "normal_tp": nt, "build_fp": bf, "build_tp": bt}
    hosts = {name for name, records in domains.items() if set(records) == {"host"}}
    features = {name: set(next(iter(next(iter(records.values()))["features"]))) for name, records in domains.items()}
    return (hosts, features, records) if include_domains else (hosts, features)


def domain_for_package(config, package, requested=None):
    """Choose one exact domain; build ancestry supplies host explicitly."""
    if not config.get("wasm"):
        return None
    available = {domain for name, domain in config["unit_domains"] if name == package}
    domain = requested or ("wasm" if "wasm" in available else "host")
    if domain not in available:
        sys.exit(f"buckify-crates: {package} has no exact {domain} unit")
    return domain

def wasm_unit_domains(config, members):
    """Read the pinned Cargo's graph only; this does not compile or run build scripts."""
    out = subprocess.run(
        ["cargo", "build", "--locked", *config["args"], "--target", WASM[1],
         "-Z", "unstable-options", "--unit-graph"],
        cwd=WS, env=dict(os.environ, RUSTC_BOOTSTRAP="1"), check=True,
        capture_output=True, text=True).stdout
    return classify_wasm_units(json.loads(out), config["packages"], members, include_domains=True)

def resolve(config, members):
    """resolve_for on every host, merged: {package: (features, {os: first-party}, {os: third-party})}.

    Features must agree across hosts. A native target has one feature set, and a
    package whose features differ by host would need two targets where cargo
    has one; that has not been needed, and is refused rather than guessed.
    """
    if config.get("wasm"):
        config["host_packages"], unit_features, config["unit_domains"] = wasm_unit_domains(config, members)
    per_host = {os_name: resolve_for(config, members, triple) for os_name, triple in config.get("triples", HOSTS)}
    out = {}
    for pkg in sorted(set().union(*per_host.values())):
        feats = {os_name: r[pkg][0] for os_name, r in per_host.items() if pkg in r}
        distinct = {json.dumps(sorted(f)) for f in feats.values()}
        if len(distinct) > 1:
            sys.exit(f"buckify-crates: {pkg} resolves with different features on {', '.join(sorted(feats))}: {feats}")
        features = next(iter(feats.values()))
        fp = {os_name: (r[pkg][1] if pkg in r else set()) for os_name, r in per_host.items()}
        tp = {os_name: (r[pkg][2] if pkg in r else set()) for os_name, r in per_host.items()}
        out[pkg] = (features, fp, tp)
    if config.get("wasm"):
        for name, (features, _, _) in out.items():
            if name not in unit_features or features != unit_features[name]:
                sys.exit(f"buckify-crates: {name} tree features do not match its exact Cargo unit; separate unit rendering is required")
    return out

def wasm_third_party_resolution(config):
    """Only actual WASM normal edges request WASM third-party features.

    Host build/proc-macro ancestry stays in the ordinary host inventory, even
    when the same first-party package also has a WASM unit.
    """
    return {name: (record["features"], {}, {WASM[0]: record["normal_tp"]})
            for (name, domain), record in config["unit_domains"].items() if domain == "wasm"}


def split_hosts(per_os):
    """(common, {os: extra}) of a per-host set: what every host has, and what each
    has besides."""
    common = set.intersection(*per_os.values()) if per_os else set()
    extra = {o: v - common for o, v in per_os.items() if v - common}
    return common, extra

def workspace_root_of(crate_dir):
    """The directory of the workspace a crate inherits `[lints] workspace = true`
    from: the nearest enclosing Cargo.toml that declares [workspace]."""
    d = crate_dir
    while True:
        manifest = d / "Cargo.toml"
        if manifest.exists() and re.search(r"^\[workspace\]", manifest.read_text(), re.M):
            return d
        if d == ROOT or d == d.parent:
            return ROOT
        d = d.parent

_LINT_FLAGS = {}

def workspace_lint_flags(ws_root):
    """rustc flags for `[workspace.lints]`, which cargo passes to every member
    that says `[lints] workspace = true`. Read by hand: no tomllib on Apple's 3.9."""
    if ws_root in _LINT_FLAGS:
        return _LINT_FLAGS[ws_root]
    text = (ws_root / "Cargo.toml").read_text()
    flags, table = [], None
    level = {"forbid": "-F", "deny": "-D", "warn": "-W", "allow": "-A"}
    for line in text.splitlines():
        header = re.match(r"^\[workspace\.lints\.(\w+)\]$", line.strip())
        if header:
            table = header.group(1)
            continue
        if line.startswith("["):
            table = None
            continue
        m = re.match(r'^([\w-]+)\s*=\s*"(\w+)"', line.strip())
        if table and m:
            lint = m.group(1).replace("-", "_")
            flags.append(f"{level[m.group(2)]}{'' if table == 'rust' else table + '::'}{lint}")
    _LINT_FLAGS[ws_root] = flags
    return flags

# The one absolute path every native first-party crate is compiled to believe is
# its CARGO_MANIFEST_DIR, and where its tests find the binaries cargo would hand
# them in CARGO_BIN_EXE_<name>. The prelude rewrites CARGO_MANIFEST_DIR into the
# building machine's own source copy, so a test binary served from the cache to
# another host would look for its fixtures on the first one; a fixed path is the
# same string on every host, and the test runner points it at the real checkout
# before running anything.
# Not under /tmp: product image-path validation refuses /tmp, and tests that
# validate a path under this root must see it pass as it does for a checkout in
# a home directory. tools/buck/native_test.bzl mounts it inside each test run's
# private namespace, so nothing is created on the host.
NATIVE_ROOT = "/mnt/gaugewright-native"

CLIPPY_NAMES = ("clippy.toml", ".clippy.toml")

def clippy_toml_for(crate_dir):
    """The clippy.toml cargo clippy would read for a crate: the nearest one at or
    above its directory, within the repository; None where there is none. Asked
    of git, so the answer is the same inside the read sandbox."""
    d = crate_dir.relative_to(ROOT)
    while True:
        for name in CLIPPY_NAMES:
            candidate = str(d / name) if str(d) != "." else name
            if candidate in tracked():
                return candidate
        if str(d) == ".":
            return None
        d = d.parent

def clippy_label(toml):
    return (":clippy-configuration" if toml in (None,) + CLIPPY_NAMES else
            ":clippy-configuration-" + re.sub(r"[^A-Za-z0-9_-]", "_", str(Path(toml).parent))) + SUFFIX

def select_deps(common, extra):
    """A deps expression: the common list, and a select() for what one host adds."""
    text = star(sorted(common))
    if not extra:
        return text
    arms = {f"prelude//os:{o}": sorted(v) for o, v in sorted(extra.items())}
    arms["DEFAULT"] = []
    return f"{text} + select({star(arms)})"

def main():
    verify_rendered_copy()
    checking = "--check" in sys.argv

    m = metadata()
    config = native_config(m)
    CELL, CHECKOUT = config["cell"], config["checkout"]
    member_ids = set(m["workspace_members"])
    # First-party: every path package the workspace builds. Members are the
    # subset cargo's --workspace lints, tests and gives binaries.
    local = {p["id"] for p in m["packages"] if p["source"] is None}
    pkgs = {p["name"]: p for p in m["packages"] if p["id"] in local}
    member_names = {p["name"] for p in m["packages"] if p["id"] in member_ids}
    PACKAGE_DIRS[:] = sorted(str(Path(p["manifest_path"]).parent.relative_to(ROOT)) for p in pkgs.values())
    closed = closed_crates(config, {n: str(Path(p["manifest_path"]).parent.relative_to(ROOT)) for n, p in pkgs.items()})
    # The closed libraries something takes, and every closed target that may
    # take one; both filled as the targets are emitted.
    closed_aliases, closed_targets = set(), set()

    def visibility(pkg):
        """A crate's targets: PUBLIC when it is open, the closed package alone
        when it is closed, which is what keeps every edge into it on the alias."""
        return json.dumps([f"//{CLOSED_PKG}:"]) if pkg in closed else '["PUBLIC"]'

    members = set(pkgs)
    configs = bar_configurations(config.get("feature-checks"))
    # A wasm build is a configuration of its own, resolved for the wasm target
    # alone: which dependencies apply, and with which features, is the wasm
    # target's answer, not a host's.
    for w in config.get("wasm", []):
        args = ["-p", w["package"]]
        if not w.get("default-features", True):
            args.append("--no-default-features")
        if w.get("features"):
            args += ["--features", ",".join(w["features"])]
        configs["wasm-" + w["package"]] = {"args": args, "edges": "normal,build", "all_targets": set(),
                                            "check_root": w["package"], "triples": [WASM], "wasm": True, "packages": m["packages"]}
    wanted_ignored = ignored_runs(config.get("ignored-tests"))
    resolved = {name: resolve(cfg, members) for name, cfg in configs.items()}

    third = render_third_party(CELL, local, [wasm_third_party_resolution(c) for c in configs.values() if c.get("wasm")])
    if checking and THIRD_PARTY.read_text() != third:
        sys.exit("third-party/Cargo.toml is not what the members' Cargo.toml files render to; "
                 f"run {RUN}, copy Cargo.lock into third-party/, and run reindeer")
    if not checking:
        THIRD_PARTY.write_text(third)

    tp = third_party_names()

    def declared_kinds(pkg, dep):
        return {d["kind"] or "normal" for d in pkgs[pkg]["dependencies"] if d["name"] == dep}

    def tp_label(name, version):
        key = tp.get((name, version))
        if key is None:
            sys.exit(f"buckify-crates: {name} {version} is not in third-party/Cargo.toml; re-run {RUN} and reindeer")
        return f"//{TP_DIR}:{key}"

    names, keys, emitted, lines, label_pkg = {}, {}, set(), [], {}

    def reaches(start, goal, cfg):
        """Whether first-party package `start` depends, however far down, on `goal`."""
        seen, todo = set(), [start]
        while todo:
            q = todo.pop()
            if q == goal:
                return True
            if q in seen or q not in resolved[cfg]:
                continue
            seen.add(q)
            todo.extend(set().union(*resolved[cfg][q][1].values()))
        return False
    index = {"feature_checks": [], "lint": [], "tests": [], "test_runs": [], "bins": {}}

    normal = lambda k: bool(k & {"normal"})
    build = lambda k: bool(k & {"build"})
    dev_only = lambda k: "dev" in k and "normal" not in k

    def edge_label(pkg, name):
        """The label another target takes library `name` of `pkg` by: its own,
        or for a closed crate its alias in the closed package."""
        if pkg not in closed:
            return ":" + name
        closed_aliases.add(name)
        return f"//{CLOSED_PKG}:{name}"

    def variant(cfg, pkg, domain=None):
        """The lib target name for pkg in cfg, emitting it (and its deps) once.

        Dependencies are visited in name order, normal then build, before the
        target itself and dev-dependencies after it, so the rendering is the
        same on every run. Memoised before the dev-dependencies are visited,
        because a crate's tests may use a crate that depends on it -- cargo
        allows the cycle, and the test target is not the library it reaches."""
        domain = domain_for_package(configs[cfg], pkg, domain)
        identity = (cfg, pkg, domain) if domain else (cfg, pkg)
        if identity in keys:
            return edge_label(pkg, keys[identity][0])
        feats, fp, tpd = resolved[cfg][pkg]
        domain_record = configs[cfg].get("unit_domains", {}).get((pkg, domain))
        if domain_record:
            feats = domain_record["features"]
        def kind(want):
            if domain_record:
                kinds = [k for k in ("normal", "build") if want({k})]
                fps = {o: sorted(set().union(*(domain_record[k + "_fp"] for k in kinds))) for o in fp}
                tps = {o: sorted(tp_label(n, v) for n, v in set().union(*(domain_record[k + "_tp"] for k in kinds))) for o in fp}
                return fps, tps
            fps = {o: sorted(d for d in fp[o] if want(declared_kinds(pkg, d))) for o in fp}
            tps = {o: sorted(tp_label(n, v) for n, v in tpd[o] if want(declared_kinds(pkg, n))) for o in tpd}
            return fps, tps
        (n_fp, n_tp), (b_fp, b_tp), (d_fp, d_tp) = kind(normal), kind(build), kind(dev_only)
        hosts = sorted(fp)
        def labels(fps, tps):
            """Visit the first-party variants in order, then (common, {os: extra})."""
            visited = {o: [variant(cfg, *d) if domain_record else variant(cfg, d) for d in fps[o]] for o in hosts}
            return visited, split_hosts({o: set(visited[o]) | set(tps[o]) for o in hosts})
        n_vis, deps = labels(n_fp, n_tp)
        b_vis, build_deps = labels(b_fp, b_tp)
        if all(len({json.dumps(x[o]) for o in hosts}) == 1 for x in (n_vis, n_tp, b_vis, b_tp)):
            # Host-independent: the key is what it was before hosts were
            # resolved separately, so an existing rendering does not move.
            o = hosts[0]
            key = json.dumps([pkg, sorted(feats), n_vis[o], n_tp[o], b_vis[o], b_tp[o]])
        else:
            key = json.dumps([pkg, sorted(feats), {o: [n_vis[o], n_tp[o], b_vis[o], b_tp[o]] for o in hosts}])
        platform = WASM_PLATFORM if domain == "wasm" else PLATFORM if domain == "host" else variant_platform(configs[cfg], pkgs[pkg])
        key = platform_variant_key(key, platform)
        if key not in names:
            # The hash only tells two targets' names apart; nothing trusts it,
            # and changing it would rename every native target in every
            # rendering. semgrep's sha1 rule does not read usedforsecurity.
            names[key] = f"rust-{pkg}" if cfg == "build" else f"rust-{pkg}--{hashlib.sha1(key.encode(), usedforsecurity=False).hexdigest()[:8]}"  # nosemgrep: python.lang.security.insecure-hash-algorithms.insecure-hash-algorithm-sha1
            emit_lib(names[key], pkg, feats, deps, build_deps, platform)
        name = names[key]
        label_pkg[edge_label(pkg, name)] = pkg
        keys[identity] = (name, feats, None, deps)
        _, dev = labels(d_fp, d_tp)
        keys[identity] = (name, feats, dev, deps)
        if domain == domain_for_package(configs[cfg], pkg):
            keys[(cfg, pkg)] = keys[identity]
        return edge_label(pkg, name)

    def plus(*parts):
        """The union of several (common, {os: extra}) dependency sets."""
        common = set().union(*(p[0] for p in parts))
        extra = {}
        for _, e in parts:
            for o, v in e.items():
                extra.setdefault(o, set()).update(v)
        return common, {o: v - common for o, v in extra.items() if v - common}

    def common(pkg):
        p = pkgs[pkg]
        crate_dir = Path(p["manifest_path"]).parent
        rel = str(crate_dir.relative_to(ROOT))
        env = {
            # rustc's --env-set (below) is unstable; this is what lets a stable
            # compiler take it.
            "RUSTC_BOOTSTRAP": "1",
            # Cargo sets CARGO, the cargo running the build, for every compile,
            # and a test that runs cargo reads it with env!(). The bare name is
            # the same on every host, so the compile stays one cache entry; the
            # test finds cargo on PATH, as a shell would.
            "CARGO": "cargo",
            "CARGO_PKG_NAME": p["name"],
            "CARGO_PKG_VERSION": p["version"],
            "CARGO_PKG_VERSION_MAJOR": p["version"].split(".")[0],
            "CARGO_PKG_VERSION_MINOR": p["version"].split(".")[1],
            "CARGO_PKG_VERSION_PATCH": p["version"].split(".")[2].split("-")[0],
            "CARGO_PKG_VERSION_PRE": "",
        }
        manifest_dir = f"{NATIVE_ROOT}/{CHECKOUT}" if rel == "." else f"{NATIVE_ROOT}/{CHECKOUT}/{rel}"
        manifest_flags = ["-Zunstable-options", f"--env-set=CARGO_MANIFEST_DIR={manifest_dir}"]
        inherits = re.search(r"^\[lints\]\s*\nworkspace\s*=\s*true", (crate_dir / "Cargo.toml").read_text(), re.M)
        lints = manifest_flags + workspace_lint_flags(workspace_root_of(crate_dir)) if inherits else manifest_flags
        return p, crate_dir, rel, env, lints, None

    def buildscript(name, pkg, feats, build_deps):
        p, crate_dir, rel, env, _, _ = common(pkg)
        custom = next((t for t in p["targets"] if "custom-build" in t["kind"]), None)
        if not custom:
            return {}, []
        bs = f"{name}-build-script"
        script = Path(custom["src_path"]).relative_to(crate_dir)
        if bs not in emitted:
            emitted.add(bs)
            if pkg in closed:
                closed_targets.add(f"{bs}-build")
            lines.extend([
                "    cargo.rust_binary(",
                f'        name = "{bs}-build",',
                f"        srcs = {files_expr([join(rel, str(script))], extra=sorted(referenced_files([crate_dir / script])))},",
                '        crate = "build_script_build",',
                f'        crate_root = "{join(rel, str(script))}",',
                f'        edition = "{p["edition"]}",',
                f"        env = {star(dict(env, CARGO_CRATE_NAME='build_script_build'))},",
                f"        features = {star(sorted(feats))},",
                f"        deps = {select_deps(*build_deps)},",
                "        visibility = [],",
                "    )",
                "    buildscript_run(",
                f'        name = "{bs}-run",',
                f'        package_name = "{p["name"]}",',
                f'        buildscript_rule = ":{bs}-build",',
                f"        env = {star(dict({k: v for k, v in env.items() if k != 'CARGO_MANIFEST_DIR'}, OPT_LEVEL='0', DEBUG='true', PROFILE='debug'))},",
                f"        features = {star(sorted(feats))},",
                f'        version = "{p["version"]}",',
                f'        local_manifest_dir = "{rel}",',
                "    )",
            ])
        return {"OUT_DIR": f"$(location :{bs}-run[out_dir])"}, [f"@$(location :{bs}-run[rustc_flags])"]

    def rule(kind, name, pkg, target, feats, deps, extra_env=None, bs=({}, []), platform=PLATFORM):
        p, crate_dir, rel, env, lints, _ = common(pkg)
        tkinds = set(target["kind"])
        if "test" in tkinds:
            srcs = target_srcs(crate_dir, "tests", target["name"])
        elif "example" in tkinds:
            srcs = target_srcs(crate_dir, "examples", target["name"])
        else:
            srcs = target_srcs(crate_dir, "code")
        crate = target["name"].replace("-", "_")
        env = dict(env, CARGO_CRATE_NAME=crate, **bs[0], **(extra_env or {}))
        if kind == "cargo.rust_binary" and "bin" in target["kind"]:
            env["CARGO_BIN_NAME"] = target["name"]
        lines.extend([
            f"    {kind}(",
            f'        name = "{name}",',
            f"        srcs = {srcs},",
            f'        crate = "{crate}",',
            f'        crate_root = "{join(rel, str(Path(target["src_path"]).relative_to(crate_dir)))}",',
            f'        edition = "{target.get("edition") or p["edition"]}",',
            f"        env = {star(env)},",
            f"        features = {star(sorted(feats))},",
            # A proc-macro crate is a library the compiler loads, and says so.
            *(["        proc_macro = True,"] if "proc-macro" in tkinds else []),
            *([f"        rustc_flags = {star(lints + bs[1])},"] if lints or bs[1] else []),
            f"        deps = {select_deps(*deps)},",
            f'        clippy_configuration = "{clippy_label(clippy_toml_for(crate_dir))}",',
            f'        default_target_platform = "{platform}",',
            f"        visibility = {visibility(pkg)},",
            "    )",
        ])
        if pkg in closed:
            closed_targets.add(name)
        clippy_tomls.add(clippy_toml_for(crate_dir))

    def emit_lib(name, pkg, feats, deps, build_deps, platform):
        p = pkgs[pkg]
        lib = next((t for t in p["targets"] if set(t["kind"]) & {"lib", "rlib", "cdylib", "proc-macro"}), None)
        bs = buildscript(name, pkg, feats, build_deps)
        if lib is None:
            names_without_lib.add(name)
            return
        rule("cargo.rust_library", name, pkg, lib, feats, deps, bs=bs, platform=platform)

    names_without_lib = set()
    clippy_tomls = set()
    doc_deps = {}
    header = [
        f"# @generated by {RUN} from the workspace's Cargo.toml files and",
        "# from the bar's own cargo invocations (scripts/section.sh). Do not edit: re-run the",
        "# script; `--check` fails when this is not what they render to (GaugeWright BUILD.md",
        "# stage 5).",
        "",
        'load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")',
        'load("@prelude//rust:cargo_package.bzl", "cargo")',
        'load("@gaugewright//tools/buck:native_test.bzl", "native_clippy_configuration", "native_lint_suite", "native_test_run", "native_test_suite"' + (', "native_doctest_run"' if config.get("doctests") else "") + ')',
        *(['load("@gaugewright//tools/buck:wasm.bzl", "wasm_module"' + (', "wasm_bindgen"' if any(w.get("bindgen") for w in config["wasm"]) else "") + ')'] if config.get("wasm") else []),
        "",
        "def native_crates():",
    ]

    for cfg_name, cfg in configs.items():
        # The bar's roots: every member for the whole-workspace configurations,
        # the one package a feature check names for the others.
        in_cfg = [pkg for pkg in sorted(resolved[cfg_name]) if pkg in member_names]
        roots = in_cfg if cfg_name in ("build", "test") else [cfg["check_root"]]
        for pkg in sorted(resolved[cfg_name]):
            variant(cfg_name, pkg)
        for pkg in roots:
            lib_name, feats, dev, normal_deps = keys[(cfg_name, pkg)]
            p = pkgs[pkg]
            has_lib = lib_name not in names_without_lib
            own = ({":" + lib_name} if has_lib else set(), {})
            bs = buildscript(lib_name, pkg, feats, (set(), {}))
            if cfg.get("wasm"):
                # The library built for the wasm target, whose `[cdylib]` is the
                # .wasm cargo's cdylib is, and wasm-bindgen over it.
                spec_ = next(w for w in config["wasm"] if w["package"] == pkg)
                # wasm-bindgen's CLI must be the version of the crate the build links.
                linked = {dep for entry in resolved[cfg_name].values() for dep in set().union(*entry[2].values())}
                bindgen = next(v for n, v in sorted(linked) if n == "wasm-bindgen")
                lines.extend([
                    "    wasm_module(",
                    f'        name = "wasm-{pkg}",',
                    f'        wasm = ":{lib_name}[cdylib]",',
                    f'        default_target_platform = "{PLATFORM}",',
                    f"        visibility = {visibility(pkg)},",
                    "    )",
                ])
                if spec_.get("bindgen"):
                    lines.extend([
                        "    wasm_bindgen(",
                        f'        name = "wasm-bindgen-{pkg}",',
                        f'        wasm = ":{lib_name}[cdylib]",',
                        f'        stem = "{pkg.replace("-", "_")}",',
                        f'        target = "{spec_["bindgen"]}",',
                        f'        version = "{bindgen}",',
                        f'        default_target_platform = "{PLATFORM}",',
                        f"        visibility = {visibility(pkg)},",
                        "    )",
                    ])
                index.setdefault("wasm", {})[pkg] = f"{CELL}//:wasm-{pkg}"
                continue
            if cfg_name not in ("build", "test") and has_lib:
                index["feature_checks"].append(f"{CELL}//:{lib_name}[check]")
            all_targets = cfg["all_targets"] == "*" or pkg in cfg["all_targets"]
            suffix = "" if cfg_name == "build" else "--" + lib_name.rsplit("--", 1)[-1] if "--" in lib_name else ""
            bins = {}
            def enabled(t):
                # cargo skips a target whose required-features are not all on.
                return set(t.get("required-features") or []) <= set(feats)
            for t in p["targets"]:
                if "bin" not in t["kind"] or (cfg_name not in ("build", "test") and not all_targets) or not enabled(t):
                    continue
                bname = f"rust-bin-{t['name']}{suffix}"
                if bname not in emitted:
                    emitted.add(bname)
                    rule("cargo.rust_binary", bname, pkg, t, feats, plus(normal_deps, own), bs=bs)
                bins[t["name"]] = bname
                if cfg_name == "test":
                    index["bins"][t["name"]] = f"{CELL}//:{bname}"
                    # --all-targets lints a binary as itself as well as under test.
                    index["lint"].append(f"{CELL}//:{bname}[clippy.txt]")
            if cfg_name == "build":
                continue
            if cfg_name == "test" and has_lib:
                index["lint"].append(f"{CELL}//:{lib_name}[clippy.txt]")
                lib_target = next(t for t in p["targets"] if set(t["kind"]) & {"lib", "rlib"} or "proc-macro" in t["kind"])
                if config.get("doctests") and lib_target.get("doctest", True) and "proc-macro" not in lib_target["kind"]:
                    # Cargo compiles a crate's doctests against its
                    # dev-dependencies as well; without them a compile_fail
                    # doctest would pass for want of a crate. Except the crate
                    # itself, and a dev-dependency that depends on it: the
                    # prelude hangs doc_deps on the library, so either would be
                    # the library depending on itself.
                    def keep(label):
                        dep = label_pkg.get(label)
                        return dep is None or (dep != pkg and not reaches(dep, pkg, "test"))
                    common_dev, extra_dev = dev
                    doc_deps[lib_name] = ({l for l in common_dev if keep(l)},
                                          {o: {l for l in v if keep(l)} for o, v in extra_dev.items()})
                    lines.extend([
                        "    native_doctest_run(",
                        f'        name = "{lib_name}-doctests",',
                        f'        doc = ":{lib_name}[doc]",',
                        f'        default_target_platform = "{PLATFORM}",',
                        "    )",
                    ])
                    index.setdefault("doctest_runs", []).append(f"{CELL}//:{lib_name}-doctests")
            if not all_targets:
                continue
            # A crate whose tests run its own build script declares it, and
            # gets it as a binary like any other: the path the build script
            # records for itself is on whichever machine ran it, which the
            # cache makes any machine.
            if cfg_name == "test" and bs[0] and ((p.get("metadata") or {}).get("native-tests") or {}).get("build-script"):
                bins["build-script-build"] = f"{lib_name}-build-script-build"
            bin_env = {f"CARGO_BIN_EXE_{b}": f"{NATIVE_ROOT}/bin/{b}" for b in bins}
            tag = lib_name.rsplit("--", 1)[-1] if "--" in lib_name else "build"
            rel = str(Path(p["manifest_path"]).parent.relative_to(ROOT))
            for t in p["targets"]:
                if not enabled(t):
                    continue
                kinds = set(t["kind"])
                if kinds & {"lib", "rlib", "proc-macro"} and t.get("test", True) and has_lib:
                    tname, deps, env = f"rust-test-{pkg}-lib--{tag}", plus(normal_deps, dev), {}
                elif "bin" in kinds and t.get("test", True):
                    tname, deps, env = f"rust-test-{pkg}-bin-{t['name']}--{tag}", plus(normal_deps, dev, own), {}
                elif "test" in kinds:
                    tname, deps, env = f"rust-test-{pkg}-{t['name']}--{tag}", plus(normal_deps, dev, own), bin_env
                elif "example" in kinds:
                    ename = f"rust-example-{pkg}-{t['name']}--{tag}"
                    if ename not in emitted:
                        emitted.add(ename)
                        rule("cargo.rust_binary", ename, pkg, t, feats, plus(normal_deps, dev, own), bs=bs)
                    if cfg_name == "test":
                        index["lint"].append(f"{CELL}//:{ename}[clippy.txt]")
                    else:
                        index["feature_checks"].append(f"{CELL}//:{ename}[check]")
                    continue
                else:
                    continue
                if tname in emitted:
                    continue
                emitted.add(tname)
                rule("native.rust_test", tname, pkg, t, feats, deps, extra_env=env, bs=bs)
                if cfg_name == "test":
                    index["tests"].append({"target": f"{CELL}//:{tname}", "cwd": rel})
                    index["lint"].append(f"{CELL}//:{tname}[clippy.txt]")
                    reach = runtime_reach(Path(p["manifest_path"]).parent)
                    # What the sources cannot show, declared by the crate itself:
                    # [package.metadata.native-tests] data = [...] in its Cargo.toml.
                    meta = (p.get("metadata") or {}).get("native-tests") or {}
                    declared = meta.get("data", [])
                    artifacts = meta.get("artifacts", {})
                    # A crate's own tree -- which, for a package at the root, is
                    # its sources and tests rather than the whole repository.
                    own_tree = ([join(rel, f) for f in ("Cargo.toml", "src/**", "tests/**")]
                                if Path(p["manifest_path"]).parent == WS else [rel + "/**"])
                    data_globs = own_tree + reach + [
                        d if d in tracked() else d + "/**" for d in declared]
                    template = [
                        "    native_test_run(",
                        f'        name = "{tname}-run",',
                        f'        test = ":{tname}",',
                        f"        bins = {star({b: ':' + n for b, n in sorted(bins.items())})},",
                        f"        artifacts = {star(dict(sorted(artifacts.items())))},",
                        f"        data = {data_expr(sorted(set(data_globs)))},",
                        f'        cell = "{CHECKOUT}",',
                        f'        crate_dir = "{rel}",',
                        f'        fixed_root = "{NATIVE_ROOT}",',
                        f'        default_target_platform = "{PLATFORM}",',
                        "    )",
                    ]
                    # A binary whose tests take long in total, declared by its
                    # crate -- [package.metadata.native-tests] shards =
                    # { <test> = N } -- runs as N actions, each a stable share
                    # of its tests on the same few cores, so it is not the
                    # one long action a bar waits on.
                    shards = int((meta.get("shards") or {}).get(t["name"], 1))
                    if shards > 1:
                        for i in range(1, shards + 1):
                            lines.extend([template[0], f'        name = "{tname}-run-{i}-of-{shards}",'] + template[2:-1]
                                         + [f'        shard = "{i}/{shards}",', "    )"])
                            index["test_runs"].append(f"{CELL}//:{tname}-run-{i}-of-{shards}")
                    else:
                        lines.extend(template)
                        index["test_runs"].append(f"{CELL}//:{tname}-run")
                    # Files a test writes for a step to read, declared by the
                    # crate: [package.metadata.native-tests.exports.<test>]
                    # filter = "...", env = { VAR = "file" }. A run of its own,
                    # of the tests the filter names, whose `[exports]` are the
                    # files, under a name a BUCK file can say.
                    export = (meta.get("exports") or {}).get(t["name"])
                    if export:
                        run = template
                        lines.extend([run[0], f'        name = "{tname}-exports-run",'] + run[2:-1] + [
                            f'        filter = "{export.get("filter", "")}",',
                            f"        exports = {star(dict(sorted(export['env'].items())))},",
                            "    )",
                            "    native.alias(",
                            f'        name = "exports-{pkg}-{t["name"]}",',
                            f'        actual = ":{tname}-exports-run[exports]",',
                            f'        default_target_platform = "{PLATFORM}",',
                            f"        visibility = {visibility(pkg)},",
                            "    )",
                        ])
                    which = (pkg, "bin" if "bin" in kinds else "test", t["name"])
                    if which in wanted_ignored:
                        run = template
                        lines.extend([run[0], f'        name = "{tname}-ignored-run",'] + run[2:-1] + [
                            "        ignored = True,",
                            f'        filter = "{wanted_ignored[which]}",',
                            "    )",
                        ])
                        index.setdefault("ignored_runs", []).append(f"{CELL}//:{tname}-ignored-run")
                else:
                    index["feature_checks"].append(f"{CELL}//:{tname}[check]")

    # The bar's Rust sections on a host that can run them this way, each as one
    # target (scripts/check.sh): every test run above, every lint report, and
    # every other configuration's check.
    local = lambda labels: star([":" + r.split("//:", 1)[-1] for r in labels])
    lines.extend([
        "    native_test_suite(",
        f'        name = "native-tests{SUFFIX}",',
        f"        runs = {local(index['test_runs'])},",
        f'        default_target_platform = "{PLATFORM}",',
        '        visibility = ["PUBLIC"],',
        "    )",
        "    native_lint_suite(",
        f'        name = "native-lints{SUFFIX}",',
        f"        reports = {local(index['lint'])},",
        f'        default_target_platform = "{PLATFORM}",',
        '        visibility = ["PUBLIC"],',
        "    )",
    ])
    if index.get("ignored_runs"):
        lines.extend([
            "    native_test_suite(",
            f'        name = "native-ignored-tests{SUFFIX}",',
            f"        runs = {local(index['ignored_runs'])},",
            f'        default_target_platform = "{PLATFORM}",',
            '        visibility = ["PUBLIC"],',
            "    )",
        ])
    if index.get("doctest_runs"):
        lines.extend([
            "    native_test_suite(",
            f'        name = "native-doctests{SUFFIX}",',
            f"        runs = {local(index['doctest_runs'])},",
            f'        default_target_platform = "{PLATFORM}",',
            '        visibility = ["PUBLIC"],',
            "    )",
        ])
    # Each library whose doctests run gets its dev-dependencies as doc_deps,
    # which the prelude hands to rustdoc and nothing else compiles against.
    for lib_name, dev_deps in sorted(doc_deps.items()):
        start = lines.index(f'        name = "{lib_name}",')
        at = next(i for i in range(start, len(lines)) if lines[i].startswith("        default_target_platform"))
        lines.insert(at, f"        doc_deps = {select_deps(*dev_deps)},")
    if index["feature_checks"]:
        lines.extend([
            "    native_test_suite(",
            f'        name = "native-feature-checks{SUFFIX}",',
            f"        runs = {local(index['feature_checks'])},",
            f'        default_target_platform = "{PLATFORM}",',
            '        visibility = ["PUBLIC"],',
            "    )",
        ])
    # What clippy reads for each first-party target, as cargo clippy finds it.
    confs = []
    for toml in sorted(clippy_tomls, key=lambda t: (t is not None, t or "")):
        confs.extend([
            "    native_clippy_configuration(",
            f'        name = "{clippy_label(toml)[1:]}",',
            *([f'        src = "{toml}",'] if toml else []),
            "    )",
        ])
    text = "\n".join(header + confs + lines + dependent_srcs(config.get("dependents", []))) + "\n"
    index_text = json.dumps(index, indent=2, sort_keys=True) + "\n"
    closed_text = closed_package(closed_aliases, closed_targets) if closed else None
    if checking and profile_opt_levels() != fixup_opt_levels():
        sys.exit(f"Cargo.toml's [profile.dev.package.*] opt-levels {profile_opt_levels()} are not what the reindeer "
                 f"fixups pass {fixup_opt_levels()}: a native build would compile them differently from cargo; "
                 "update third-party/fixups/<crate>/fixups.toml and re-run reindeer")
    if checking:
        workspace, third_lock = lock_packages(WS / "Cargo.lock"), lock_packages(WS / "third-party/Cargo.lock")
        if workspace != third_lock:
            sys.exit("third-party/Cargo.lock pins different packages from Cargo.lock; copy Cargo.lock into third-party/ and re-run reindeer")
        verify_git_materialization(WS / "Cargo.lock", WS / "third-party/BUCK")
        if not OUT.exists() or OUT.read_text() != text or not INDEX.exists() or INDEX.read_text() != index_text:
            sys.exit(f"native-crates.bzl or native-bar.json is not what Cargo.toml and scripts/section.sh render to; run {RUN}")
        if (CLOSED_BUCK.read_text() if CLOSED_BUCK.exists() else None) != closed_text:
            sys.exit(f"{CLOSED_PKG}/BUCK is not what Cargo.toml and the mirror's published paths render to; run {RUN}")
        print("native-crates.bzl and native-bar.json match Cargo.toml and the bar")
        return
    OUT.write_text(text)
    INDEX.write_text(index_text)
    if closed_text is not None:
        CLOSED_BUCK.parent.mkdir(parents=True, exist_ok=True)
        CLOSED_BUCK.write_text(closed_text)
    elif CLOSED_BUCK.exists():
        CLOSED_BUCK.unlink()
    print(f"wrote native-crates.bzl and native-bar.json: {len(member_names)} members, {len(pkgs)} first-party crates, "
          f"{len(configs)} configurations, {len(index['tests'])} test binaries, {len(index['feature_checks'])} feature checks")

if __name__ == "__main__":
    main()
