#!/usr/bin/env python3
"""Render a cargo workspace's crates as native Buck2 targets (GaugeWright BUILD.md stages 5 and 6).

This file is rendered from tools/shared-checks/buckify-crates.py in the
GaugeWright repository, which owns it, by `node tools/shared-checks.mjs --write`.
It verifies itself on every run, so a local edit fails; change it there.

Cargo.toml stays the one source of truth for what a crate is and what it depends
on; this renders it into native-crates.bzl, which the root BUCK calls. `--check`
exits non-zero when the committed file is not what Cargo.toml renders to, which
is how the two are kept from drifting apart.

What differs between repositories is stated once, in the workspace's own
Cargo.toml, and nowhere else:

    [workspace.metadata.native]
    cell = "whipplescript"            # the Buck2 cell this checkout is
    checkout = "whipplescript-src"    # its repository id
    feature-checks = "feature-builds" # optional: the scripts/section.sh case
                                      # whose `cargo check -p` lines are the
                                      # bar's other configurations

The targets live in the ROOT package because the crates reach outside their own
directories at compile time -- include_str!("../../../examples/...") and a build
script reading a sibling tree -- and Buck2 lets a package declare only files
beneath it. From the root, every file sits at its real path, so every relative
include resolves exactly as it does under cargo.

First-party is every path package the workspace builds, which is more than its
members: a crate taken by `path` from a vendored peer (a `platform/` submodule)
is compiled from this checkout as cargo compiles it, while only the members are
linted, tested and given binaries, as `--workspace` does.

Third-party crates are //third-party:<name>, generated by reindeer from
third-party/Cargo.toml. The build has the workspace's default features, which is
what `cargo build --workspace` builds, resolved for Linux and macOS; where the
two resolve differently the difference is a select().
"""
import hashlib, json, os, re, subprocess, sys
from pathlib import Path

SOURCE_DIGEST = "4f14add27b61fab63a868319c09641a58248c085606308db86587d2ccd4c5a9c"
PLACEHOLDER = "__EXPECTED_DIGEST__"

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "native-crates.bzl"
INDEX = ROOT / "native-bar.json"
THIRD_PARTY = ROOT / "third-party/Cargo.toml"
PLATFORM = "prelude//platforms:default"
INCLUDE = re.compile(r'include(?:_str|_bytes)?!\(\s*"([^"]+)"\s*\)|#\[path\s*=\s*"([^"]+)"\]')
# The hosts a native build runs on, as the prelude's OS constraints name them.
# A workspace resolves the same on both almost everywhere; where it does not,
# the rendering says so with a select() rather than being one host's answer.
HOSTS = [("linux", "x86_64-unknown-linux-gnu"), ("macos", "aarch64-apple-darwin")]

def verify_rendered_copy():
    """Fail if this rendered copy has drifted from the source that owns it."""
    if SOURCE_DIGEST == PLACEHOLDER:
        return
    body = Path(__file__).read_text().replace(
        f'SOURCE_DIGEST = "{SOURCE_DIGEST}"', f'SOURCE_DIGEST = "{PLACEHOLDER}"', 1)
    if hashlib.sha256(body.encode()).hexdigest() != SOURCE_DIGEST:
        sys.exit("scripts/buckify-crates.py has been edited locally. It is generated from "
                 "tools/shared-checks/buckify-crates.py in the GaugeWright repository; change it "
                 "there and re-render with `node tools/shared-checks.mjs --write`.")

def metadata(*extra):
    out = subprocess.run(["cargo", "metadata", "--format-version", "1", "--locked", *extra],
                         cwd=ROOT, check=True, capture_output=True, text=True).stdout
    return json.loads(out)

def native_config(m):
    """[workspace.metadata.native] from the workspace's Cargo.toml."""
    native = (m.get("metadata") or {}).get("native") or {}
    missing = [k for k in ("cell", "checkout") if not native.get(k)]
    if missing:
        sys.exit(f"buckify-crates: [workspace.metadata.native] in Cargo.toml must name {' and '.join(missing)}")
    return native

def join(rel, path):
    """A repository-relative path under a crate directory, which is `.` for a
    package at the root."""
    return path if rel == "." else f"{rel}/{path}"

def third_party_names():
    """The names third-party/Cargo.toml gives each (package, version).

    Read through cargo rather than a TOML parser, so the script needs nothing
    newer than the Python every gate host has (Apple's is 3.9).
    """
    out = subprocess.run(["cargo", "metadata", "--format-version", "1", "--no-deps",
                          "--manifest-path", str(ROOT / "third-party/Cargo.toml")],
                         check=True, capture_output=True, text=True).stdout
    names = {}
    for d in json.loads(out)["packages"][0]["dependencies"]:
        names[(d["name"], d["req"].lstrip("="))] = d.get("rename") or d["name"]
    return names

def referenced_files(roots):
    """Every file the Rust files in roots embed or `#[path]` in, followed through
    the Rust files found that way. Repository-relative paths.

    The path the source names, not whether it exists on disk: whether it does is
    the compiler's question, and asking the filesystem would make this output
    depend on files the check does not declare (it runs sandboxed). Asked of git
    instead, which answers the same inside the sandbox: a path nothing tracks is
    either no file at all -- the text of a test fixture that happens to spell an
    include -- or one only a build makes, and in neither case a source.
    """
    found, queue, seen = set(), list(roots), set()
    while queue:
        rs = queue.pop()
        if rs in seen or not rs.exists():
            continue
        seen.add(rs)
        for m in INCLUDE.finditer(rs.read_text(errors="replace")):
            target = Path(os.path.normpath(rs.parent / (m.group(1) or m.group(2))))
            try:
                rel = str(target.relative_to(ROOT))
            except ValueError:
                continue
            if rel in tracked():
                found.add(rel)
            if target.suffix == ".rs":
                queue.append(target)
    return found

_TRACKED = None

def tracked():
    """Every tracked path, from git: the same list inside the read sandbox as
    outside it, where the filesystem shows only what a section declares. A
    submodule's files are listed as its own, so a vendored peer is seen too."""
    global _TRACKED
    if _TRACKED is None:
        out = subprocess.run(["git", "ls-files", "-z", "--recurse-submodules"], cwd=ROOT, check=True, capture_output=True).stdout
        _TRACKED = set(out.decode().split("\0")) - {""}
    return _TRACKED

def tracked_dir(path):
    prefix = path.rstrip("/") + "/"
    return any(t.startswith(prefix) for t in tracked())

def subpackages():
    """Directories below the root that are Buck2 packages of their own: a vendored
    peer that carries its BUCK file is one. A glob from the root package stops
    at such a directory and matches nothing inside it, so what a target reads
    there is named file by file instead -- which Buck2 allows the root package
    only when the cell's .buckconfig lists it in project.package_boundary_exceptions."""
    return sorted({str(Path(t).parent) for t in tracked()
                   if Path(t).name in ("BUCK", "BUCK.v2") and str(Path(t).parent) != "."})

def in_subpackage(pattern):
    base = pattern[:-3] if pattern.endswith("/**") else pattern
    return any(base == d or base.startswith(d + "/") for d in subpackages())

def expand(pattern):
    """The tracked files a `dir/**` or single-file pattern names."""
    if pattern.endswith("/**"):
        prefix = pattern[:-2]
        return {t for t in tracked() if t.startswith(prefix)}
    return {pattern} & tracked()

def data_expr(patterns):
    """A test run's data: the declared trees, less build output, named file by
    file where they lie inside a subpackage."""
    inside = [p for p in patterns if in_subpackage(p)]
    outside = [p for p in patterns if not in_subpackage(p)]
    text = f"glob({star(outside)}, exclude = {star(['**/target/**', '**/node_modules/**'])})"
    if inside:
        text += " + " + files_expr(inside)[: -len(" + []")]
    return text

def files_expr(patterns, exclude=(), extra=()):
    """A srcs expression: a glob where a glob reaches, and the files themselves
    where the patterns lie inside a subpackage, where it would not."""
    inside = [p for p in patterns if in_subpackage(p)]
    outside = [p for p in patterns if not in_subpackage(p)]
    parts = []
    if outside:
        ex = [x for x in exclude if not in_subpackage(x)]
        parts.append(f"glob({star(outside)}{', exclude = ' + star(ex) if ex else ''})")
    if inside:
        dropped = set().union(*(expand(x) for x in exclude)) if exclude else set()
        named = set().union(*(expand(p) for p in inside)) - dropped
        named = {n for n in named if "/target/" not in f"/{n}" and "/node_modules/" not in f"/{n}"}
        parts.append(star(sorted(named)))
    parts.append(star(list(extra)))
    return " + ".join(parts)

# The directories of every first-party package, repository-relative; set in
# main() before anything reads it. A package's own files stop where another's
# begin, which matters only for a package at the root.
PACKAGE_DIRS = []

def own_rust_files(crate_dir, skip=("target",)):
    """The crate's Rust files: not those of a package nested inside it, and not
    build output."""
    rel = crate_dir.relative_to(ROOT)
    nested = [ROOT / d for d in PACKAGE_DIRS if d != "." and Path(d) != rel and (ROOT / d).is_relative_to(crate_dir)]
    for rs in crate_dir.rglob("*.rs"):
        parts = rs.relative_to(crate_dir).parts
        if any(s in parts for s in skip) or "node_modules" in parts:
            continue
        if any(rs.is_relative_to(n) for n in nested):
            continue
        yield rs

RUNTIME_REACH = re.compile(r'"((?:\.\./)+)([A-Za-z0-9_.-]+)')

def runtime_reach(crate_dir):
    """Repository directories a crate's code reaches by relative path at run
    time: the top-level ones (examples/, std/, ...) and sibling crates. Read
    from its sources, resolved both from the file and from the crate (a
    CARGO_MANIFEST_DIR join is relative to the crate). Generous by design: the
    test run's mount holds only what is declared, so a miss fails loudly and a
    surplus only costs a rerun.
    """
    own = crate_dir.relative_to(ROOT)
    packages = [Path(d) for d in PACKAGE_DIRS if d != "."]
    found = set()
    for rs in own_rust_files(crate_dir):
        for m in RUNTIME_REACH.finditer(rs.read_text(errors="replace")):
            for base in (rs.parent, crate_dir):
                try:
                    rel = Path(os.path.normpath(base / (m.group(1) + m.group(2)))).relative_to(ROOT)
                except ValueError:
                    continue
                if not rel.parts or rel.parts[0] in ("target", ".git"):
                    continue
                inside = next((p for p in packages if rel == p or rel.is_relative_to(p)), None)
                if inside is not None:
                    if inside != own and tracked_dir(str(inside)):
                        found.add(str(inside))
                elif any(p.parts[0] == rel.parts[0] for p in packages):
                    # Under a directory that holds packages, such as crates/,
                    # but in none of them: what is named there is not a
                    # package, and the directory is not the crate's to read.
                    continue
                elif tracked_dir(rel.parts[0]):
                    found.add(rel.parts[0])
    return sorted(found)

def target_srcs(crate_dir, kind, name=None):
    """What one target reads, as tightly as cargo would rebuild it.

    A library or binary: the crate minus its tests, examples and benches (its
    own non-Rust files, such as the store's SQL migrations, stay in). An
    integration test or example: its own file and directory, and the shared
    helper directories tests use. Plus everything any of those embeds or
    `#[path]`s in, wherever it lives. Editing one test file therefore rebuilds
    that test, not the library every other target depends on.

    A package at the root of the repository is the exception: its directory is
    the whole repository, so its library is its src/ and what that embeds.
    """
    rel = str(crate_dir.relative_to(ROOT))
    if kind == "code" and rel == ".":
        patterns, exclude = ["src/**"], []
        roots = [f for f in own_rust_files(crate_dir / "src")]
    elif kind == "code":
        patterns = [f"{rel}/**"]
        exclude = [f"{rel}/{d}/**" for d in ("tests", "examples", "benches", "target")]
        roots = [f for f in own_rust_files(crate_dir)
                 if not any(f.is_relative_to(crate_dir / d) for d in ("tests", "examples", "benches", "target"))]
    else:
        base = crate_dir / kind
        patterns = [join(rel, f"{kind}/{name}.rs"), join(rel, f"{kind}/{name}/**")]
        if kind == "tests":
            patterns += [join(rel, "tests/support/**"), join(rel, "tests/common/**")]
        exclude = []
        roots = [base / f"{name}.rs"] + [f for d in (base / name, base / "support", base / "common") if d.is_dir() for f in d.rglob("*.rs")]
    def is_covered(path):
        for pat in patterns:
            if pat.endswith("/**") and path.startswith(pat[:-2]) and not any(path.startswith(x[:-2]) for x in exclude):
                return True
            if path == pat:
                return True
        return False
    extra = sorted(p for p in referenced_files(roots) if not is_covered(p))
    return files_expr(patterns, exclude, extra)

def patch_sections():
    """The workspace's [patch.*] tables, verbatim. Cargo applies a patch only from
    the top-level workspace, so the third-party manifest must carry it to resolve
    the same packages."""
    text = (ROOT / "Cargo.toml").read_text()
    return [m.group(0).rstrip("\n") for m in re.finditer(r'^\[patch\.[^\]]+\]\n(?:[^\[\n].*\n|\n)*', text, re.M)]

def render_third_party(cell, local):
    """third-party/Cargo.toml: every external crate a first-party package names,
    pinned at the version the workspace lockfile resolves, with the union of the
    features they ask for. Resolved with every feature on, so an optional
    dependency (custodian's cryptoki, behind `pkcs11`) is pinned too. A package
    wanted at two versions keeps its name at the newer one and takes
    `<name>-<maj>_<min>` at the older, which reindeer turns into a second public
    target. A dependency the lockfile resolves for no one -- an optional one no
    feature turns on, a non-member's dev-dependency -- is not wanted.
    """
    m = metadata("--all-features")
    pkgs = {p["id"]: p for p in m["packages"]}
    nodes = {n["id"]: n for n in m["resolve"]["nodes"]}
    want = {}
    for pid in sorted(local, key=lambda i: (pkgs[i]["name"], i)):
        p = pkgs[pid]
        if pid not in nodes:
            continue
        resolved = {}
        for d in nodes[pid]["deps"]:
            resolved.setdefault(pkgs[d["pkg"]]["name"], set()).add(pkgs[d["pkg"]]["version"])
        for d in p["dependencies"]:
            if d.get("path"):
                continue
            versions = resolved.get(d["name"], set())
            if not versions:
                continue
            # The leading components the requirement names, compared as
            # components: "1" is not a prefix of "10.0.0".
            wanted = d["req"].lstrip("^=~ ").split(".")[:2]
            # Each version the declaration resolved to takes its features: two
            # versions of one crate are two crates, and a feature one of them
            # has is not the other's to be asked for.
            for v in {v for v in versions if v.split(".")[:len(wanted)] == wanted} or versions:
                w = want.setdefault(d["name"], {}).setdefault(v, {"features": set(), "default": False, "targets": set()})
                w["features"] |= set(d["features"])
                w["default"] |= d["uses_default_features"]
                if d.get("target"):
                    w["targets"].add(d["target"])
                else:
                    w["targets"].add(None)

    def key(v):
        return [int(x) for x in v.split("-")[0].split(".")]

    def spec(name, version, w, rename=None):
        parts = ([f'package = "{name}"'] if rename else []) + [f'version = "={version}"']
        if not w["default"]:
            parts.append("default-features = false")
        if w["features"]:
            parts.append("features = [" + ", ".join(f'"{f}"' for f in sorted(w["features"])) + "]")
        return f'{rename or name} = {{ {", ".join(parts)} }}'

    lines = [
        "# @generated by scripts/buckify-crates.py from the workspace's Cargo.toml files.",
        "# Reindeer's input for the native third-party targets (GaugeWright BUILD.md",
        "# stage 5), not a crate: the workspace excludes it. After re-rendering, copy",
        "# ../Cargo.lock here and run `reindeer --third-party-dir third-party buckify`.",
        "[package]", f'name = "{cell}-third-party"', 'version = "0.0.0"', 'edition = "2021"',
        "publish = false", "", "[lib]", 'path = "top.rs"', "", "[dependencies]",
    ]
    by_target = {}
    for name in sorted(want):
        vs = sorted(want[name], key=key)
        # A version any member takes unconditionally is a plain dependency;
        # one taken only under a cfg is listed under each of them.
        targets = set().union(*(want[name][v]["targets"] for v in vs))
        out = [spec(name, vs[-1], want[name][vs[-1]])] + [
            spec(name, v, want[name][v], rename=f"{name}-{v.split('.')[0]}_{v.split('.')[1]}") for v in vs[:-1]]
        if None not in targets:
            for t in sorted(targets):
                by_target.setdefault(t, []).extend(out)
        else:
            lines += out
    for t in sorted(by_target):
        lines += ["", f"[target.'{t}'.dependencies]"] + by_target[t]
    for patch in patch_sections():
        lines += ["", patch]
    return "\n".join(lines) + "\n"

def profile_opt_levels():
    """{crate: opt-level} from Cargo.toml's [profile.dev.package.<crate>] tables."""
    text = (ROOT / "Cargo.toml").read_text()
    out = {}
    for m in re.finditer(r'^\[profile\.dev\.package\.([A-Za-z0-9_-]+)\]\n((?:[^\[\n].*\n)*)', text, re.M):
        lvl = re.search(r'^opt-level\s*=\s*"?(\w+)"?', m.group(2), re.M)
        if lvl:
            out[m.group(1)] = lvl.group(1)
    return out

def fixup_opt_levels():
    """{crate: opt-level} the generated third-party targets pass to rustc.

    Read from third-party/BUCK, which the native-crates section declares, rather
    than from the fixups reindeer rendered it from, which a sandboxed section in
    the root package cannot declare. A crate appears once per version.
    """
    out = {}
    text = (ROOT / "third-party/BUCK").read_text()
    for block in text.split("\ncargo.rust_library(")[1:]:
        name = re.search(r'name = "([^"]+)"', block)
        flag = re.search(r'"-Copt-level=(\w+)"', block.split("\n)\n", 1)[0])
        if name and flag:
            out[re.sub(r"-\d+(\.\d+)*(-[^-]+)?$", "", name.group(1))] = flag.group(1)
    return out

def lock_packages(path):
    """(name, version, checksum) of every registry or git package a Cargo.lock pins.

    Parsed by hand rather than with tomllib, which the Python on the Mac gate
    host (Apple's 3.9) does not have; a lockfile's [[package]] blocks are flat.
    """
    found, cur = set(), {}
    for line in list(path.read_text().splitlines()) + ["[[package]]"]:
        if line == "[[package]]":
            if cur.get("source", "").startswith(('"registry+', '"git+')):
                found.add((cur["name"], cur["version"], cur.get("checksum", "")))
            cur = {}
        elif " = " in line:
            k, v = line.split(" = ", 1)
            cur[k] = v
    return found

def star(value):
    return json.dumps(value, indent=4).replace("\n", "\n    ")

# ---- configurations: what the bar actually compiles --------------------------

def bar_configurations(section):
    """Every cargo configuration the bar compiles Rust in, read from the bar.

    `build` is `cargo build --workspace`; `test` is what nextest and
    `clippy --workspace --all-targets` compile (dev-dependencies on). The rest are
    the `cargo check -p ...` lines of the named section.sh case, so the list of
    variants has one owner: the bar.
    """
    configs = {
        "build": {"args": ["--workspace"], "edges": "normal,build", "all_targets": set()},
        "test": {"args": ["--workspace"], "edges": "normal,build,dev", "all_targets": "*"},
    }
    if not section:
        return configs
    text = (ROOT / "scripts/section.sh").read_text()
    block = text[text.index(f"  {section})"):]
    block = block[: block.index(";;")]
    for line in block.splitlines():
        m = re.search(r"cargo check (-p \S+.*)$", line.strip())
        if not m:
            continue
        args = m.group(1).split()
        pkg = args[1]
        all_targets = "--all-targets" in args
        args = [a for a in args if a != "--all-targets"]
        name = "check-" + "-".join(a.lstrip("-") for a in args[1:])
        configs[name] = {
            "args": args,
            "edges": "normal,build,dev" if all_targets else "normal,build",
            "all_targets": {pkg} if all_targets else set(),
            "check_root": pkg,
        }
    return configs

TREE_LINE = re.compile(r"^(\d+)(\S+) v(\S+)( \(([^)]*)\))?\|(.*?)( \(\*\))?$")

def resolve_for(config, members, triple):
    """{package: (features, first-party deps, third-party deps)} for one configuration on one host."""
    out = subprocess.run(
        ["cargo", "tree", "--locked", *config["args"], "-e", config["edges"],
         "--prefix", "depth", "--format", "{p}|{f}", "--target", triple],
        cwd=ROOT, check=True, capture_output=True, text=True).stdout
    resolved, stack = {}, []
    for raw in out.splitlines():
        m = TREE_LINE.match(raw)
        if not m:
            continue
        depth, name, version = int(m.group(1)), m.group(2), m.group(3)
        features = set(filter(None, m.group(6).split(",")))
        del stack[depth:]
        if stack:
            parent = stack[-1]
            if parent in members:
                entry = resolved.setdefault(parent, [None, set(), set()])
                if name in members:
                    entry[1].add(name)
                else:
                    entry[2].add((name, version))
        if name in members:
            entry = resolved.setdefault(name, [None, set(), set()])
            entry[0] = features if entry[0] is None else entry[0] | features
        stack.append(name)
    return {k: (v[0] or set(), v[1], v[2]) for k, v in resolved.items()}

def resolve(config, members):
    """resolve_for on every host, merged: {package: (features, {os: first-party}, {os: third-party})}.

    Features must agree across hosts. A native target has one feature set, and a
    package whose features differ by host would need two targets where cargo
    has one; that has not been needed, and is refused rather than guessed.
    """
    per_host = {os_name: resolve_for(config, members, triple) for os_name, triple in HOSTS}
    out = {}
    for pkg in sorted(set().union(*per_host.values())):
        feats = {os_name: r[pkg][0] for os_name, r in per_host.items() if pkg in r}
        distinct = {json.dumps(sorted(f)) for f in feats.values()}
        if len(distinct) > 1:
            sys.exit(f"buckify-crates: {pkg} resolves with different features on {', '.join(sorted(feats))}: {feats}")
        features = next(iter(feats.values()))
        fp = {os_name: (r[pkg][1] if pkg in r else set()) for os_name, r in per_host.items()}
        tp = {os_name: (r[pkg][2] if pkg in r else set()) for os_name, r in per_host.items()}
        out[pkg] = (features, fp, tp)
    return out

def split_hosts(per_os):
    """(common, {os: extra}) of a per-host set: what every host has, and what each
    has besides."""
    common = set.intersection(*per_os.values()) if per_os else set()
    extra = {o: v - common for o, v in per_os.items() if v - common}
    return common, extra

def workspace_root_of(crate_dir):
    """The directory of the workspace a crate inherits `[lints] workspace = true`
    from: the nearest enclosing Cargo.toml that declares [workspace]."""
    d = crate_dir
    while True:
        manifest = d / "Cargo.toml"
        if manifest.exists() and re.search(r"^\[workspace\]", manifest.read_text(), re.M):
            return d
        if d == ROOT or d == d.parent:
            return ROOT
        d = d.parent

_LINT_FLAGS = {}

def workspace_lint_flags(ws_root):
    """rustc flags for `[workspace.lints]`, which cargo passes to every member
    that says `[lints] workspace = true`. Read by hand: no tomllib on Apple's 3.9."""
    if ws_root in _LINT_FLAGS:
        return _LINT_FLAGS[ws_root]
    text = (ws_root / "Cargo.toml").read_text()
    flags, table = [], None
    level = {"forbid": "-F", "deny": "-D", "warn": "-W", "allow": "-A"}
    for line in text.splitlines():
        header = re.match(r"^\[workspace\.lints\.(\w+)\]$", line.strip())
        if header:
            table = header.group(1)
            continue
        if line.startswith("["):
            table = None
            continue
        m = re.match(r'^([\w-]+)\s*=\s*"(\w+)"', line.strip())
        if table and m:
            lint = m.group(1).replace("-", "_")
            flags.append(f"{level[m.group(2)]}{'' if table == 'rust' else table + '::'}{lint}")
    _LINT_FLAGS[ws_root] = flags
    return flags

# The one absolute path every native first-party crate is compiled to believe is
# its CARGO_MANIFEST_DIR, and where its tests find the binaries cargo would hand
# them in CARGO_BIN_EXE_<name>. The prelude rewrites CARGO_MANIFEST_DIR into the
# building machine's own source copy, so a test binary served from the cache to
# another host would look for its fixtures on the first one; a fixed path is the
# same string on every host, and the test runner points it at the real checkout
# before running anything.
# Not under /tmp: product image-path validation refuses /tmp, and tests that
# validate a path under this root must see it pass as it does for a checkout in
# a home directory. tools/buck/native_test.bzl mounts it inside each test run's
# private namespace, so nothing is created on the host.
NATIVE_ROOT = "/mnt/gaugewright-native"

CLIPPY_NAMES = ("clippy.toml", ".clippy.toml")

def clippy_toml_for(crate_dir):
    """The clippy.toml cargo clippy would read for a crate: the nearest one at or
    above its directory, within the repository; None where there is none. Asked
    of git, so the answer is the same inside the read sandbox."""
    d = crate_dir.relative_to(ROOT)
    while True:
        for name in CLIPPY_NAMES:
            candidate = str(d / name) if str(d) != "." else name
            if candidate in tracked():
                return candidate
        if str(d) == ".":
            return None
        d = d.parent

def clippy_label(toml):
    return ":clippy-configuration" if toml in (None,) + CLIPPY_NAMES else \
        ":clippy-configuration-" + re.sub(r"[^A-Za-z0-9_-]", "_", str(Path(toml).parent))

def select_deps(common, extra):
    """A deps expression: the common list, and a select() for what one host adds."""
    text = star(sorted(common))
    if not extra:
        return text
    arms = {f"prelude//os:{o}": sorted(v) for o, v in sorted(extra.items())}
    arms["DEFAULT"] = []
    return f"{text} + select({star(arms)})"

def main():
    verify_rendered_copy()
    checking = "--check" in sys.argv

    m = metadata()
    config = native_config(m)
    CELL, CHECKOUT = config["cell"], config["checkout"]
    member_ids = set(m["workspace_members"])
    # First-party: every path package the workspace builds. Members are the
    # subset cargo's --workspace lints, tests and gives binaries.
    local = {p["id"] for p in m["packages"] if p["source"] is None}
    pkgs = {p["name"]: p for p in m["packages"] if p["id"] in local}
    member_names = {p["name"] for p in m["packages"] if p["id"] in member_ids}
    PACKAGE_DIRS[:] = sorted(str(Path(p["manifest_path"]).parent.relative_to(ROOT)) for p in pkgs.values())

    third = render_third_party(CELL, local)
    if checking and THIRD_PARTY.read_text() != third:
        sys.exit("third-party/Cargo.toml is not what the members' Cargo.toml files render to; "
                 "run scripts/buckify-crates.py, copy Cargo.lock into third-party/, and run reindeer")
    if not checking:
        THIRD_PARTY.write_text(third)

    tp = third_party_names()
    members = set(pkgs)
    configs = bar_configurations(config.get("feature-checks"))
    resolved = {name: resolve(cfg, members) for name, cfg in configs.items()}

    def declared_kinds(pkg, dep):
        return {d["kind"] or "normal" for d in pkgs[pkg]["dependencies"] if d["name"] == dep}

    def tp_label(name, version):
        key = tp.get((name, version))
        if key is None:
            sys.exit(f"buckify-crates: {name} {version} is not in third-party/Cargo.toml; re-run scripts/buckify-crates.py and reindeer")
        return f"//third-party:{key}"

    names, keys, emitted, lines = {}, {}, set(), []
    index = {"feature_checks": [], "lint": [], "tests": [], "test_runs": [], "bins": {}}

    normal = lambda k: bool(k & {"normal"})
    build = lambda k: bool(k & {"build"})
    dev_only = lambda k: "dev" in k and "normal" not in k

    def variant(cfg, pkg):
        """The lib target name for pkg in cfg, emitting it (and its deps) once.

        Dependencies are visited in name order, normal then build, before the
        target itself and dev-dependencies after it, so the rendering is the
        same on every run. Memoised before the dev-dependencies are visited,
        because a crate's tests may use a crate that depends on it -- cargo
        allows the cycle, and the test target is not the library it reaches."""
        if (cfg, pkg) in keys:
            return ":" + keys[(cfg, pkg)][0]
        feats, fp, tpd = resolved[cfg][pkg]
        def kind(want):
            fps = {o: sorted(d for d in fp[o] if want(declared_kinds(pkg, d))) for o in fp}
            tps = {o: sorted(tp_label(n, v) for n, v in tpd[o] if want(declared_kinds(pkg, n))) for o in tpd}
            return fps, tps
        (n_fp, n_tp), (b_fp, b_tp), (d_fp, d_tp) = kind(normal), kind(build), kind(dev_only)
        hosts = sorted(fp)
        def labels(fps, tps):
            """Visit the first-party variants in order, then (common, {os: extra})."""
            visited = {o: [variant(cfg, d) for d in fps[o]] for o in hosts}
            return visited, split_hosts({o: set(visited[o]) | set(tps[o]) for o in hosts})
        n_vis, deps = labels(n_fp, n_tp)
        b_vis, build_deps = labels(b_fp, b_tp)
        if all(len({json.dumps(x[o]) for o in hosts}) == 1 for x in (n_vis, n_tp, b_vis, b_tp)):
            # Host-independent: the key is what it was before hosts were
            # resolved separately, so an existing rendering does not move.
            o = hosts[0]
            key = json.dumps([pkg, sorted(feats), n_vis[o], n_tp[o], b_vis[o], b_tp[o]])
        else:
            key = json.dumps([pkg, sorted(feats), {o: [n_vis[o], n_tp[o], b_vis[o], b_tp[o]] for o in hosts}])
        if key not in names:
            names[key] = f"rust-{pkg}" if cfg == "build" else f"rust-{pkg}--{hashlib.sha1(key.encode()).hexdigest()[:8]}"
            emit_lib(names[key], pkg, feats, deps, build_deps)
        name = names[key]
        keys[(cfg, pkg)] = (name, feats, None, deps)
        _, dev = labels(d_fp, d_tp)
        keys[(cfg, pkg)] = (name, feats, dev, deps)
        return ":" + name

    def plus(*parts):
        """The union of several (common, {os: extra}) dependency sets."""
        common = set().union(*(p[0] for p in parts))
        extra = {}
        for _, e in parts:
            for o, v in e.items():
                extra.setdefault(o, set()).update(v)
        return common, {o: v - common for o, v in extra.items() if v - common}

    def common(pkg):
        p = pkgs[pkg]
        crate_dir = Path(p["manifest_path"]).parent
        rel = str(crate_dir.relative_to(ROOT))
        env = {
            # rustc's --env-set (below) is unstable; this is what lets a stable
            # compiler take it.
            "RUSTC_BOOTSTRAP": "1",
            # Cargo sets CARGO, the cargo running the build, for every compile,
            # and a test that runs cargo reads it with env!(). The bare name is
            # the same on every host, so the compile stays one cache entry; the
            # test finds cargo on PATH, as a shell would.
            "CARGO": "cargo",
            "CARGO_PKG_NAME": p["name"],
            "CARGO_PKG_VERSION": p["version"],
            "CARGO_PKG_VERSION_MAJOR": p["version"].split(".")[0],
            "CARGO_PKG_VERSION_MINOR": p["version"].split(".")[1],
            "CARGO_PKG_VERSION_PATCH": p["version"].split(".")[2].split("-")[0],
            "CARGO_PKG_VERSION_PRE": "",
        }
        manifest_dir = f"{NATIVE_ROOT}/{CHECKOUT}" if rel == "." else f"{NATIVE_ROOT}/{CHECKOUT}/{rel}"
        manifest_flags = ["-Zunstable-options", f"--env-set=CARGO_MANIFEST_DIR={manifest_dir}"]
        inherits = re.search(r"^\[lints\]\s*\nworkspace\s*=\s*true", (crate_dir / "Cargo.toml").read_text(), re.M)
        lints = manifest_flags + workspace_lint_flags(workspace_root_of(crate_dir)) if inherits else manifest_flags
        return p, crate_dir, rel, env, lints, None

    def buildscript(name, pkg, feats, build_deps):
        p, crate_dir, rel, env, _, _ = common(pkg)
        custom = next((t for t in p["targets"] if "custom-build" in t["kind"]), None)
        if not custom:
            return {}, []
        bs = f"{name}-build-script"
        script = Path(custom["src_path"]).relative_to(crate_dir)
        if bs not in emitted:
            emitted.add(bs)
            lines.extend([
                "    cargo.rust_binary(",
                f'        name = "{bs}-build",',
                f"        srcs = {files_expr([join(rel, str(script))], extra=sorted(referenced_files([crate_dir / script])))},",
                '        crate = "build_script_build",',
                f'        crate_root = "{join(rel, str(script))}",',
                f'        edition = "{p["edition"]}",',
                f"        env = {star(dict(env, CARGO_CRATE_NAME='build_script_build'))},",
                f"        features = {star(sorted(feats))},",
                f"        deps = {select_deps(*build_deps)},",
                "        visibility = [],",
                "    )",
                "    buildscript_run(",
                f'        name = "{bs}-run",',
                f'        package_name = "{p["name"]}",',
                f'        buildscript_rule = ":{bs}-build",',
                f"        env = {star(dict({k: v for k, v in env.items() if k != 'CARGO_MANIFEST_DIR'}, OPT_LEVEL='0', DEBUG='true', PROFILE='debug'))},",
                f"        features = {star(sorted(feats))},",
                f'        version = "{p["version"]}",',
                f'        local_manifest_dir = "{rel}",',
                "    )",
            ])
        return {"OUT_DIR": f"$(location :{bs}-run[out_dir])"}, [f"@$(location :{bs}-run[rustc_flags])"]

    def rule(kind, name, pkg, target, feats, deps, extra_env=None, bs=({}, [])):
        p, crate_dir, rel, env, lints, _ = common(pkg)
        tkinds = set(target["kind"])
        if "test" in tkinds:
            srcs = target_srcs(crate_dir, "tests", target["name"])
        elif "example" in tkinds:
            srcs = target_srcs(crate_dir, "examples", target["name"])
        else:
            srcs = target_srcs(crate_dir, "code")
        crate = target["name"].replace("-", "_")
        env = dict(env, CARGO_CRATE_NAME=crate, **bs[0], **(extra_env or {}))
        if kind == "cargo.rust_binary" and "bin" in target["kind"]:
            env["CARGO_BIN_NAME"] = target["name"]
        lines.extend([
            f"    {kind}(",
            f'        name = "{name}",',
            f"        srcs = {srcs},",
            f'        crate = "{crate}",',
            f'        crate_root = "{join(rel, str(Path(target["src_path"]).relative_to(crate_dir)))}",',
            f'        edition = "{target.get("edition") or p["edition"]}",',
            f"        env = {star(env)},",
            f"        features = {star(sorted(feats))},",
            # A proc-macro crate is a library the compiler loads, and says so.
            *(["        proc_macro = True,"] if "proc-macro" in tkinds else []),
            *([f"        rustc_flags = {star(lints + bs[1])},"] if lints or bs[1] else []),
            f"        deps = {select_deps(*deps)},",
            f'        clippy_configuration = "{clippy_label(clippy_toml_for(crate_dir))}",',
            f'        default_target_platform = "{PLATFORM}",',
            '        visibility = ["PUBLIC"],',
            "    )",
        ])
        clippy_tomls.add(clippy_toml_for(crate_dir))

    def emit_lib(name, pkg, feats, deps, build_deps):
        p = pkgs[pkg]
        lib = next((t for t in p["targets"] if set(t["kind"]) & {"lib", "rlib", "cdylib", "proc-macro"}), None)
        bs = buildscript(name, pkg, feats, build_deps)
        if lib is None:
            names_without_lib.add(name)
            return
        rule("cargo.rust_library", name, pkg, lib, feats, deps, bs=bs)

    names_without_lib = set()
    clippy_tomls = set()
    header = [
        "# @generated by scripts/buckify-crates.py from the workspace's Cargo.toml files and",
        "# from the bar's own cargo invocations (scripts/section.sh). Do not edit: re-run the",
        "# script; `--check` fails when this is not what they render to (GaugeWright BUILD.md",
        "# stage 5).",
        "",
        'load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")',
        'load("@prelude//rust:cargo_package.bzl", "cargo")',
        'load("@gaugewright//tools/buck:native_test.bzl", "native_clippy_configuration", "native_lint_suite", "native_test_run", "native_test_suite")',
        "",
        "def native_crates():",
    ]

    for cfg_name, cfg in configs.items():
        # The bar's roots: every member for the whole-workspace configurations,
        # the one package a feature check names for the others.
        in_cfg = [pkg for pkg in sorted(resolved[cfg_name]) if pkg in member_names]
        roots = in_cfg if cfg_name in ("build", "test") else [cfg["check_root"]]
        for pkg in sorted(resolved[cfg_name]):
            variant(cfg_name, pkg)
        for pkg in roots:
            lib_name, feats, dev, normal_deps = keys[(cfg_name, pkg)]
            p = pkgs[pkg]
            has_lib = lib_name not in names_without_lib
            own = ({":" + lib_name} if has_lib else set(), {})
            bs = buildscript(lib_name, pkg, feats, (set(), {}))
            if cfg_name not in ("build", "test") and has_lib:
                index["feature_checks"].append(f"{CELL}//:{lib_name}[check]")
            all_targets = cfg["all_targets"] == "*" or pkg in cfg["all_targets"]
            suffix = "" if cfg_name == "build" else "--" + lib_name.rsplit("--", 1)[-1] if "--" in lib_name else ""
            bins = {}
            def enabled(t):
                # cargo skips a target whose required-features are not all on.
                return set(t.get("required-features") or []) <= set(feats)
            for t in p["targets"]:
                if "bin" not in t["kind"] or (cfg_name not in ("build", "test") and not all_targets) or not enabled(t):
                    continue
                bname = f"rust-bin-{t['name']}{suffix}"
                if bname not in emitted:
                    emitted.add(bname)
                    rule("cargo.rust_binary", bname, pkg, t, feats, plus(normal_deps, own), bs=bs)
                bins[t["name"]] = bname
                if cfg_name == "test":
                    index["bins"][t["name"]] = f"{CELL}//:{bname}"
                    # --all-targets lints a binary as itself as well as under test.
                    index["lint"].append(f"{CELL}//:{bname}[clippy.txt]")
            if cfg_name == "build":
                continue
            if cfg_name == "test" and has_lib:
                index["lint"].append(f"{CELL}//:{lib_name}[clippy.txt]")
            if not all_targets:
                continue
            # A crate whose tests run its own build script declares it, and
            # gets it as a binary like any other: the path the build script
            # records for itself is on whichever machine ran it, which the
            # cache makes any machine.
            if cfg_name == "test" and bs[0] and ((p.get("metadata") or {}).get("native-tests") or {}).get("build-script"):
                bins["build-script-build"] = f"{lib_name}-build-script-build"
            bin_env = {f"CARGO_BIN_EXE_{b}": f"{NATIVE_ROOT}/bin/{b}" for b in bins}
            tag = lib_name.rsplit("--", 1)[-1] if "--" in lib_name else "build"
            rel = str(Path(p["manifest_path"]).parent.relative_to(ROOT))
            for t in p["targets"]:
                if not enabled(t):
                    continue
                kinds = set(t["kind"])
                if kinds & {"lib", "rlib", "proc-macro"} and t.get("test", True) and has_lib:
                    tname, deps, env = f"rust-test-{pkg}-lib--{tag}", plus(normal_deps, dev), {}
                elif "bin" in kinds and t.get("test", True):
                    tname, deps, env = f"rust-test-{pkg}-bin-{t['name']}--{tag}", plus(normal_deps, dev, own), {}
                elif "test" in kinds:
                    tname, deps, env = f"rust-test-{pkg}-{t['name']}--{tag}", plus(normal_deps, dev, own), bin_env
                elif "example" in kinds:
                    ename = f"rust-example-{pkg}-{t['name']}--{tag}"
                    if ename not in emitted:
                        emitted.add(ename)
                        rule("cargo.rust_binary", ename, pkg, t, feats, plus(normal_deps, dev, own), bs=bs)
                    if cfg_name == "test":
                        index["lint"].append(f"{CELL}//:{ename}[clippy.txt]")
                    else:
                        index["feature_checks"].append(f"{CELL}//:{ename}[check]")
                    continue
                else:
                    continue
                if tname in emitted:
                    continue
                emitted.add(tname)
                rule("native.rust_test", tname, pkg, t, feats, deps, extra_env=env, bs=bs)
                if cfg_name == "test":
                    index["tests"].append({"target": f"{CELL}//:{tname}", "cwd": rel})
                    index["lint"].append(f"{CELL}//:{tname}[clippy.txt]")
                    reach = runtime_reach(Path(p["manifest_path"]).parent)
                    # What the sources cannot show, declared by the crate itself:
                    # [package.metadata.native-tests] data = [...] in its Cargo.toml.
                    meta = (p.get("metadata") or {}).get("native-tests") or {}
                    declared = meta.get("data", [])
                    artifacts = meta.get("artifacts", {})
                    # A crate's own tree -- which, for a package at the root, is
                    # its sources and tests rather than the whole repository.
                    own_tree = ["Cargo.toml", "src/**", "tests/**"] if rel == "." else [rel + "/**"]
                    data_globs = own_tree + [d + "/**" for d in reach] + [
                        d if d in tracked() else d + "/**" for d in declared]
                    lines.extend([
                        "    native_test_run(",
                        f'        name = "{tname}-run",',
                        f'        test = ":{tname}",',
                        f"        bins = {star({b: ':' + n for b, n in sorted(bins.items())})},",
                        f"        artifacts = {star(dict(sorted(artifacts.items())))},",
                        f"        data = {data_expr(sorted(set(data_globs)))},",
                        f'        cell = "{CHECKOUT}",',
                        f'        crate_dir = "{rel}",',
                        f'        fixed_root = "{NATIVE_ROOT}",',
                        f'        default_target_platform = "{PLATFORM}",',
                        "    )",
                    ])
                    index["test_runs"].append(f"{CELL}//:{tname}-run")
                else:
                    index["feature_checks"].append(f"{CELL}//:{tname}[check]")

    # The bar's Rust sections on a host that can run them this way, each as one
    # target (scripts/check.sh): every test run above, every lint report, and
    # every other configuration's check.
    local = lambda labels: star([":" + r.split("//:", 1)[-1] for r in labels])
    lines.extend([
        "    native_test_suite(",
        '        name = "native-tests",',
        f"        runs = {local(index['test_runs'])},",
        f'        default_target_platform = "{PLATFORM}",',
        '        visibility = ["PUBLIC"],',
        "    )",
        "    native_lint_suite(",
        '        name = "native-lints",',
        f"        reports = {local(index['lint'])},",
        f'        default_target_platform = "{PLATFORM}",',
        '        visibility = ["PUBLIC"],',
        "    )",
    ])
    if index["feature_checks"]:
        lines.extend([
            "    native_test_suite(",
            '        name = "native-feature-checks",',
            f"        runs = {local(index['feature_checks'])},",
            f'        default_target_platform = "{PLATFORM}",',
            '        visibility = ["PUBLIC"],',
            "    )",
        ])
    # What clippy reads for each first-party target, as cargo clippy finds it.
    confs = []
    for toml in sorted(clippy_tomls, key=lambda t: (t is not None, t or "")):
        confs.extend([
            "    native_clippy_configuration(",
            f'        name = "{clippy_label(toml)[1:]}",',
            *([f'        src = "{toml}",'] if toml else []),
            "    )",
        ])
    text = "\n".join(header + confs + lines) + "\n"
    index_text = json.dumps(index, indent=2, sort_keys=True) + "\n"
    if checking and profile_opt_levels() != fixup_opt_levels():
        sys.exit(f"Cargo.toml's [profile.dev.package.*] opt-levels {profile_opt_levels()} are not what the reindeer "
                 f"fixups pass {fixup_opt_levels()}: a native build would compile them differently from cargo; "
                 "update third-party/fixups/<crate>/fixups.toml and re-run reindeer")
    if checking:
        workspace, third_lock = lock_packages(ROOT / "Cargo.lock"), lock_packages(ROOT / "third-party/Cargo.lock")
        if workspace != third_lock:
            sys.exit("third-party/Cargo.lock pins different packages from Cargo.lock; copy Cargo.lock into third-party/ and re-run reindeer")
        if not OUT.exists() or OUT.read_text() != text or not INDEX.exists() or INDEX.read_text() != index_text:
            sys.exit("native-crates.bzl or native-bar.json is not what Cargo.toml and scripts/section.sh render to; run scripts/buckify-crates.py")
        print("native-crates.bzl and native-bar.json match Cargo.toml and the bar")
        return
    OUT.write_text(text)
    INDEX.write_text(index_text)
    print(f"wrote native-crates.bzl and native-bar.json: {len(member_names)} members, {len(pkgs)} first-party crates, "
          f"{len(configs)} configurations, {len(index['tests'])} test binaries, {len(index['feature_checks'])} feature checks")

if __name__ == "__main__":
    main()
